### ISSUE TITLE
Make TypeScript Definitions

### ISSUE THREAD

**Issue by kevinclarkneudesic** [brainhubeu/react-carousel#105]
**Is your feature request related to a problem? Please describe.**
Typescript
After module is installed, add line declare module '@brainhubeu/react-carousel'; to file with .d.ts extension.

This is not helpful because what would be better is actual ts definitions or writing the library in ts.

**Describe the solution you'd like**
A d.ts file added to the solution

**Describe alternatives you've considered**
Other carousel libraries.

**Comment by piotr-s-brainhub** [comment]
Thanks for reporting this.
Unfortunately we don't have enough time to resolve this issue.
Anyway a PR is more than welcome.

**Comment by jackall3n** [comment]
I've created added this library to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37617

**Comment by piotr-s-brainhub** [comment]
Much thanks @jackall3n 

so now can we close this issue?

**Comment by jackall3n** [comment]
Yes I think so :)

**Comment by piotr-s-brainhub** [comment]
@kevinclarkneudesic @jackall3n 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
