### ISSUE TITLE
Make draggable slides an option

### ISSUE THREAD

**Issue by patricksimonian** [brainhubeu/react-carousel#107]
**Is your feature request related to a problem? Please describe.**
My carousel is not for images but rather containers that have links to other pages. On desktop the drag feature doesn't provide a great ux. It'd be great to have the draggable as an option and have the carousel controlled only by buttons if necessary

**Comment by piotr-s-brainhub** [comment]
Thanks for reporting this.
Unfortunately we don't have enough time to resolve this issue.
Anyway a PR is more than welcome.

**Comment by Lukasz-pluszczewski** [comment]
Draggable is an option: you can set prop `draggable={false}` to disable it (https://brainhubeu.github.io/react-carousel/docs/examples/draggable)

**Comment by piotr-s-brainhub** [comment]
@patricksimonian 

does it work for you?

**Comment by patricksimonian** [comment]
@piotr-s-brainhub sorry I'll take a look into this tonight. Was away for the weekend!

**Comment by piotr-s-brainhub** [comment]
@patricksimonian 

OK, we'll be waiting

**Comment by piotr-s-brainhub** [comment]
@patricksimonian 

have you checked this?

**Comment by pierzchalatomasz** [comment]
Closing this issue. `draggable={false}` option is the solution.
