### ISSUE TITLE
Support for Styled components ?

### ISSUE THREAD

**Issue by kevinseabourne** [brainhubeu/react-carousel#108]
Hi i'm loving this carousel you guys made !! but it would be awesome in the future if you added support for styled components instead of using your css file.

**Comment by piotr-s-brainhub** [comment]
Thanks for reporting this.
Unfortunately we don't have enough time to resolve this issue.
Anyway a PR is more than welcome.

**Comment by piotr-s-brainhub** [comment]
@kevinseabourne 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
