### ISSUE TITLE
Library does not seem to support <form>

### ISSUE THREAD

**Issue by C-CG** [brainhubeu/react-carousel#110]
Hi there,

it seems that when you add a form or input to a slide (div) you are not actually able to type anything into the boxes (clicking does nothing). 

Thanks, Calvin.

**Comment by C-CG** [comment]
Things such as buttons work on a slide, just seems odd that forms or inputs do not.

**Comment by piotr-s-brainhub** [comment]
Thanks for reporting this.
Unfortunately we don't have enough time to resolve this issue.
Anyway a PR is more than welcome.

Moreover it would be great to provide more info like:
- browser with version
- OS with version
- reproduction steps
- a video or at least screenshots

**Comment by C-CG** [comment]
> Thanks for reporting this.
> Unfortunately we don't have enough time to resolve this issue.
> Anyway a PR is more than welcome.
> 
> Moreover it would be great to provide more info like:
> 
> * browser with version
> * OS with version
> * reproduction steps
> * a video or at least screenshots

Hi,

**Comment by piotr-s-brainhub** [comment]
@C-CG 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by GnanaAjana** [comment]
onMouseDown - event 

there is e.preventDefault() -> it restricts the onChange event for form
