### ISSUE TITLE
Number of dots question

### ISSUE THREAD

**Issue by zackphilipps** [brainhubeu/react-carousel#111]
**Is your feature request related to a problem? Please describe.**
First of all, awesome component. My main problem so far is this: I'm not sure why you have to supply the number of dots as a prop to this component. With Slick, for instance, this value is computed by the plugin. The number of dots is a particular pain point because that needs to change if `slidesPerPage` is changing per breakpoint.

**Describe the solution you'd like**
I'd like the component to compute these values for me.

Any thoughts? Happy to open a PR if no one can get to it.

**Comment by piotr-s-brainhub** [comment]
Thanks for this suggestion.
A PR would be very welcome.

**Comment by udaypydi** [comment]
Hi @piotr-s-brainhub 

This has been fixed in PR:
https://github.com/brainhubeu/react-carousel/pull/128

Thanks

**Comment by piotr-s-brainhub** [comment]
thanks @udaypydi

**Comment by pierzchalatomasz** [comment]
Closing this bug, since it's fixed but I opened another one that might be related - https://github.com/brainhubeu/react-carousel/issues/172

**Comment by piotr-s-brainhub** [comment]
@zackphilipps 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
