### ISSUE TITLE
Cannot read property 'NODE_ENV' of undefined

### ISSUE THREAD

**Issue by Leksat** [brainhubeu/react-carousel#115]
We got the following error on a project using https://www.npmjs.com/package/react-styleguidist
```
Cannot read property 'NODE_ENV' of undefined
```
The error made the Styleguide not usable.

After some investigation, we have found that the error appeared after we added `@brainhubeu/react-carousel` to the project.

I guess the issue does not come from `@brainhubeu/react-carousel`, but from some of the dependencies. Because there is no `NODE_ENV` usages in `react-carousel/src`. But it's really hard to find the true source of the error.

Anyway, I have found a quick solution here: https://github.com/webpack/webpack/issues/2446#issuecomment-239657071

Will provide a PR.

<hr>

To reproduce the error, clone https://github.com/Leksat/react-carousel-test, run `yarn && yarn styleguidist build`, and open index.html in the generated `styleguide` directory.

This project was setup as follows:
```
yarn init --yes
yarn add react-styleguidist @brainhubeu/react-carousel webpack react react-dom
# add default styleguide.config.js
# create a react component and import @brainhubeu/react-carousel into it
```

**Comment by piotr-s-brainhub** [comment]
Thanks for reporting this.

A PR is very welcome.

**Comment by Leksat** [comment]
PR is there already: https://github.com/brainhubeu/react-carousel/pull/116

**Comment by pierzchalatomasz** [comment]
Closing this issue - this change doesn't break anything and there's no new reports since Jul 26, 2019

**Comment by piotr-s-brainhub** [comment]
@Leksat 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
