### ISSUE TITLE
Prevent vertical scrolling while touch swiping

### ISSUE THREAD

**Issue by shlaing** [brainhubeu/react-carousel#119]
while swiping on mobile, the page slides up and down at the same time as the carousel moving left (or right).

It'd be great to be able to lock down the vertical scrolling while horizontal movement is happening. Any suggestions?

Please kindly test with mobile. you will be realised the issue.

Thanks.

**Comment by piotr-s-brainhub** [comment]
Thanks @shlaing for reporting.

Could you provide some more details:
- OS with version
- browser with version
- version of `@brainhubeu/react-carousel`
- code using `@brainhubeu/react-carousel`
- a video or at least screenshots

**Comment by piotr-s-brainhub** [comment]
@shlaing ?

**Comment by piotr-s-brainhub** [comment]
I tested the newest version (demo) with iPhone and for me it works correctly.

**Comment by piotr-s-brainhub** [comment]
@shlaing 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
