### ISSUE TITLE
Trigger click link when drag the carousel

### ISSUE THREAD

**Issue by panacholn** [brainhubeu/react-carousel#131]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/131)

when drag the carousel, it always trigger click link if the slide items is anchor tag

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/20856232?v=4' alt='piotr-s-brainhub' width=24 height=24> piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($5.00)

### Submitted pull Requests
- [#195 Fix/dont click on drag](https://issuehunt.io/r/brainhubeu/react-carousel/pull/195)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by piotr-s-brainhub** [comment]
Thanks @panacholn for reporting.
Could you provide more data?
- OS with version
- browser with version
- `react-carousel` version
- code using `react-carousel`
- a video or at least some screenshots

**Comment by johnatrevcontent** [comment]
Also seeing this behavior. Can I hook the drag event of this component so that I can check to see if it's dragging and prevent my click?

Codesandbox:

https://codesandbox.io/s/dreamy-framework-4it5h

**Comment by piotr-s-brainhub** [comment]
@johnatrevcontent 

in the codesandbox, after dragging, I see `www.google.com refused to connect.` - is there the same behaviour on your side?

**Comment by johnatrevcontent** [comment]
@piotr-s-brainhub

Yes, I see the same behavior from it. I'm looking for a way to prevent that click when drag finishes if possible. Thanks for looking into this.

**Comment by piotr-s-brainhub** [comment]
@panacholn @johnatrevcontent 

So you want the anchor to still be working if it's just clicked but if it's dragged and dropped, it shouldn't redirect to the href link?

**Comment by johnatrevcontent** [comment]
Yes, this is the behavior I would expect.

**Comment by CHaNGeTe** [comment]
Can you try with https://github.com/brainhubeu/react-carousel/pull/195 ?

**Comment by johnatrevcontent** [comment]
I'll give this a look as soon as possible. Thanks guys!

**Comment by piotr-s-brainhub** [comment]
I just validated it on https://brainhubeu.github.io/react-carousel and it's fixed.

**Comment by piotr-s-brainhub** [comment]
@panacholn @johnatrevcontent 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by piotr-s-brainhub** [comment]
@CHaNGeTe 

I have a question: are you able to withdraw any funds from the issuehunt?
I ask because after writing to info@issuehunt.io, asking them for an invoice and waiting more than one week, I still have no reply.
And in order to withdraw any funds, it's required to send an email to info@issuehunt.io as well.
