### ISSUE TITLE
Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by Tsury** [brainhubeu/react-carousel#148]
Some users are experiencing this issue, latest version.
Not sure how to reproduce, maybe add a null check before accessing it?
Happens here: https://github.com/brainhubeu/react-carousel/blob/faa8210e8eb5ce3635c3854151eba1aa27828d44/src/components/Carousel.js#L286

**Comment by piotr-s-brainhub** [comment]
Thanks for reporting this issue.
You're welcome to open a PR.

In order to have reproduction steps, you can insert a condition checking for null and log data like state, browser version, datetime.

**Comment by piotr-s-brainhub** [comment]
@Tsury 

do you still encounter this issue?

**Comment by piotr-s-brainhub** [comment]
@Tsury 

As you didn't reply, I close this issue but feel free to reopen it when you encounter this problem again.

**Comment by Tsury** [comment]
I don't think I encounter it anymore

**Comment by piotr-s-brainhub** [comment]
@Tsury 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
