### ISSUE TITLE
upgrade major versions of dependencies

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#152]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/152)

We need this PR https://github.com/brainhubeu/react-carousel/pull/91 to have a passing build.
Moreover, nothing can be broken, even if it's not covered by any test.

In order to contribute, please create a branch in your fork from `renovate/major-all-dependencies` and open a PR to `renovate/major-all-dependencies`.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/20856232?v=4' alt='piotr-s-brainhub' width=24 height=24> piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Sbabureddy** [comment]
may I use npm-check-updates package?

**Comment by piotr-s-brainhub** [comment]
@Sbabureddy 

There's no need for `npm-check-updates` because renovate has already updated them.
The work in this issue is to update the `react-carousel` codebase to be compatible with the new major versions which have often breaking changes.

**Comment by piotr-s-brainhub** [comment]
@jamsinclair 

building GH pages failed https://circleci.com/gh/brainhubeu/react-carousel/1342

**Comment by jamsinclair** [comment]
Ah interesting! Thanks @piotr-s-brainhub, I'll take a look after the weekend.

**Comment by jamsinclair** [comment]
Sorry I couldn't find a fix to the problem. There must be something I'm not seeing. Good luck trying to solve it!

**Comment by katiawheeler** [comment]
Is this done and published? I am running `1.10.51` and am still getting this warning.

**Comment by piotr-s-brainhub** [comment]
@katiawheeler 

No, some major versions are already upgraded, some others are in this PR but the remaining ones need some work to be upgraded.

**Comment by piotr-s-brainhub** [comment]
@jamsinclair 

I reverted your PR and upgraded major versions of of dependencies where it was straightforward.
So now only a few of them remain, mainly related with react and webpack https://github.com/brainhubeu/react-carousel/pull/190

**Comment by piotr-s-brainhub** [comment]
@jamsinclair @katiawheeler 

Now only `gatsby` needs upgrading so I close this issue in favor of https://github.com/brainhubeu/react-carousel/issues/282

Any of you is welcome to ugprade `gatsby`.

Besides that, there are some babel dependencies in `docs-www/package.json` which aren't upgraded because of the `gatsby@1`.
