### ISSUE TITLE
Error on swipe on dots and thumbnails example

### ISSUE THREAD

**Issue by bojan88** [brainhubeu/react-carousel#156]
**Describe the bug**
Swiping on carousel is not working and it's trowing a console error

**To Reproduce**
1. Go to [Dots](https://brainhubeu.github.io/react-carousel/docs/examples/dots) or [Thumbnails](https://brainhubeu.github.io/react-carousel/docs/examples/thumbnails) example
2. Try to swipe
3. The error is present in the browser console, and swipe is not working properly (image is following the cursor).

**Expected behavior**
Carousel image is changed

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/1783133/67061766-5565c280-f12f-11e9-8add-8dc432ee4930.png)

**Desktop (please complete the following information):**
 - Linux
 - All. Tested in Chrome and Firefox
 - All versions

**Comment by pierzchalatomasz** [comment]
Closing, since it's fixed

**Comment by piotr-s-brainhub** [comment]
@bojan88 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
