### ISSUE TITLE
Touch swipe broken on iOS Safari

### ISSUE THREAD

**Issue by fandy** [brainhubeu/react-carousel#158]
To reproduce: sliding on the multiple items doc demos on Safari on an iPhoneX doesn't work. Single items work as long as you're not zoomed.

**Comment by piotr-s-brainhub** [comment]
@fandy 

Thanks.
Could you provide the following?
- iOS version
- Safari version
- `@brainhubeu/react-carousel` version
- a video or some screenshots

**Comment by piotr-s-brainhub** [comment]
I tested `react-carousel`, all the subpages of the demo with Safari for iOS (iPhone).
I found only that issue https://github.com/brainhubeu/react-carousel/issues/181 so I close this issue.

**Comment by piotr-s-brainhub** [comment]
@fandy 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
