### ISSUE TITLE
Breakpoints missing in TypeScript definitions

### ISSUE THREAD

**Issue by FinnGu** [brainhubeu/react-carousel#159]
**Describe the bug**
The prop `breakpoints` is missing from the types definitions. Compilation fails with the following error: 
```
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<CarouselProps>): default', gave the following error.
    Type '{ children: Element[]; centered: true; infinite: true; slidesPerPage: number; slidesPerScroll: number; stopAutoPlayOnHover: true; offset: number; autoPlay: number; value: number; onChange: (e: number) => void; breakpoints: { ...; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<default> & Readonly<CarouselProps> & Readonly<{ children?: ReactNode; }>'.
      Property 'breakpoints' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<default> & Readonly<CarouselProps> & Readonly<{ children?: ReactNode; }>'.
  Overload 2 of 2, '(props: CarouselProps, context?: any): default', gave the following error.
    Type '{ children: Element[]; centered: true; infinite: true; slidesPerPage: number; slidesPerScroll: number; stopAutoPlayOnHover: true; offset: number; autoPlay: number; value: number; onChange: (e: number) => void; breakpoints: { ...; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<default> & Readonly<CarouselProps> & Readonly<{ children?: ReactNode; }>'.
      Property 'breakpoints' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<default> & Readonly<CarouselProps> & Readonly<{ children?: ReactNode; }>'.  TS2769
```

**Expected behavior**
The prop should be added to the types definitions file so that compilation works.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Firefox
 - Version: @brainhubeu/react-carousel 1.10.27, @types/brainhubeu__react-carousel 1.10.0

**Comment by piotr-s-brainhub** [comment]
@FinnGu 

Thanks for reporting this.
Could you also provide Windows, Chrome and Firefox versions?

If you know, how to fix this, you're more than welcome to open a PR.

**Comment by piotr-s-brainhub** [comment]
@nik72619c 

I guess it's this file https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/brainhubeu__react-carousel/index.d.ts

**Comment by nik72619c** [comment]
thanks for the help :)

**Comment by FinnGu** [comment]
I'm using:
* Windows 10 Pro (v10.0.18362)
* Chrome (v78.0.3904.70)
* Firefox (v70.0)

But it is probably irrelevant as it is not a display bug.

**Comment by FinnGu** [comment]
@nik72619c I'm not sure what you mean. Do you want me to provide a code snippet that will fail?

**Comment by nik72619c** [comment]
I just checked the live project and didnt see the crash. Does it fail silently in the console ?

**Comment by FinnGu** [comment]
![grafik](https://user-images.githubusercontent.com/10939247/67887689-0fa3f380-fb4c-11e9-9778-f765680a3ca9.png)

Nothing silent about this :D

I am using the carousel as follows: 
```
<Carousel
    centered
    infinite
    slidesPerPage={3}
    slidesPerScroll={1}
    stopAutoPlayOnHover
    offset={30}
    autoPlay={3000}
    value={this.state.value}
    onChange={(e) => this.setState({
        value: e,
    })}
    breakpoints={{
        992: { // these props will be applied when screen width is less than 1000px
            slidesPerPage: 2
        },
        540: {
            slidesPerPage: 1,
            arrows: true,
            autoPlay: 0
        },
    }}
>
    <div>1</div>
    <div>2</div>
    <div>3</div>
    <div>4</div>
    <div>5</div>
    <div>6</div>
</Carousel>
```

**Comment by nik72619c** [comment]
shall i add `breakpoints: any` in the prop definitions ?

**Comment by nik72619c** [comment]
I guess this might prevent breakage :). Please do check and let me know of any changes

**Comment by FinnGu** [comment]
I just installed the newest version and everything works now 👍

**Comment by piotr-s-brainhub** [comment]
@FinnGu @nik72619c 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by FinnGu** [comment]
> @FinnGu @nik72619c
> 
> Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

Sure :)
