### ISSUE TITLE
Clear itemWidth setting with breakpoints

### ISSUE THREAD

**Issue by yuyanghh** [brainhubeu/react-carousel#161]
Hi~ Thanks for a great package!

After searching breakpoints and itemWidth related issue, I may miss an approach to "clean up" some itemWidth settings via applying breakpoints.

e.g.
I would like to have width-fixed carousel card on pc and scale up it to 100% width on mobiles

    <Carousel
        itemWidth={640}
        breakpoints={{
            767: {
                itemWidth: ??
            }
        }}> ...

Is it possible to use "null" or 0 to unset itemWidth?

**Comment by piotr-s-brainhub** [comment]
If it's not in README or demo, I guess it's not possible but you can check it and tell your observations.

**Comment by yuyanghh** [comment]
Currently, I use a responsive variable for itemWidth to achieve the same effect! Thx!

**Comment by piotr-s-brainhub** [comment]
@yuyanghh 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
