### ISSUE TITLE
React-carousel causes touch issues with GOOGLE-MAPS

### ISSUE THREAD

**Issue by shelooks16** [brainhubeu/react-carousel#163]
**Describe the bug**
When using the library with google maps API, google map touch behavior becomes broken. For example, it doesn't matter what options you supply to google maps (like gestureHandling), it won't work as expected on touch devices if `<Carousel />` is present somewhere inside the code.

**To Reproduce**
1. Use simple https://github.com/adrianmcli/nano-react-app
2. Install the library and add google maps API
3. Insert `<Carousel />` component and init google map
4. See the problem on touch devices (also with chrome dev tools)

Repo to reproduce: https://github.com/shelooks16/react-carousel-touch-issue
replace `const api = "API-KEY";` with a google-api key

**Expected behavior**
To not broke google map touch behavior?

**Screenshots**
![broken-map](https://user-images.githubusercontent.com/33040081/69754355-fa73b200-1155-11ea-8d35-bf8d6d6a54ac.gif)

I deployed 2 web-pages:
carousel imported: https://with-imported-carousel-issue.surge.sh/
carousel is not imported: https://without-imported-carousel-issue.surge.sh/

**Additional context**
Tried with carousel v1.10.27 and v1.10.20. React v16.9.0

**Comment by shelooks16** [comment]
I quickly went through the versions
<= 1.10.10-s work OK
>= v1.10.11 doesn't work
So the problem lies under v1.10.11

**Comment by piotr-s-brainhub** [comment]
@shelooks16 

Thanks for reporting it and fixing.
It's really amazing you have even deployed both projects.

I checked in Safari for iOS that https://without-imported-carousel-issue.surge.sh/ works but https://with-imported-carousel-issue.surge.sh/ even causes Safari to hang.

**Comment by pierzchalatomasz** [comment]
It seems to be already resolved, so I'm closing the issue

**Comment by pierzchalatomasz** [comment]
Issue is partially resolved - the problem still exists on mobile devices.

**Comment by piotr-s-brainhub** [comment]
@shelooks16 

so does `@brainhubeu/react-carousel` work correctly with google maps for any version?

**Comment by shelooks16** [comment]
@piotr-s-brainhub 

hello again. With different versions results are the next:

```
***browser**
Brave Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

gmaps - 3.38
1.10.27 - fail
1.10.28 - fail
1.10.29 - fail
1.10.30 - fail
1.10.31 - works
1.10.32 - works
1.10.33 - works
1.10.34 - works
1.10.35 - works

gmaps - 3.39
1.10.27 - fail
1.10.28 - fail
1.10.29 - fail
1.10.30 - fail
1.10.31 - works
1.10.32 - works
1.10.33 - works
1.10.34 - works
1.10.35 - works
```

So far haven't seen this issue after #164

**Comment by piotr-s-brainhub** [comment]
Thanks @shelooks16 ,
I just tested that on iPhone so it works for me (previously it was hanging).

@pierzchalatomasz does it work for you (google maps with carousel imported) on mobile devices?

**Comment by piotr-s-brainhub** [comment]
@shelooks16 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by shelooks16** [comment]
> @shelooks16
> 
> Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

Just filled the form

**Comment by pierzchalatomasz** [comment]
> @pierzchalatomasz does it work for you (google maps with carousel imported) on mobile devices?
It seems to be working
