### ISSUE TITLE
Bad positioning of dots

### ISSUE THREAD

**Issue by pierzchalatomasz** [brainhubeu/react-carousel#170]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/170)

**Describe the bug**
Dots on the one of examples on a demo page are positioned badly.

**To Reproduce**
1. Go to https://brainhubeu.github.io/react-carousel/docs/examples/simpleDots/
2. Look at the dots :)

**Expected behavior**
Dots should be placed below the carousel but they are placed on the right side.

**Screenshots**
<img width="1056" alt="Screen Shot 2020-01-02 at 10 09 06 AM" src="https://user-images.githubusercontent.com/9852085/71659821-43b4b400-2d49-11ea-9ef8-5bdc89126daa.png">

**Desktop (please complete the following information):**
 - OS: [macOS 10.14.6]
 - Browser [Chrome]
 - Version [79.0.3945.88]

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/20856232?v=4' alt='piotr-s-brainhub' width=24 height=24> piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($5.00)

### Submitted pull Requests
- [#173 Fix dot positions](https://issuehunt.io/r/brainhubeu/react-carousel/pull/173)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by piotr-s-brainhub** [comment]
it's fixed now

<img width="1277" alt="Screenshot 2020-01-10 at 23 40 58" src="https://user-images.githubusercontent.com/20856232/72191541-c4874600-3402-11ea-9cd9-8430cba340f7.png">

**Comment by piotr-s-brainhub** [comment]
@9greg

I have a question: are you able to withdraw any funds from the issuehunt?
I ask because after writing to info@issuehunt.io, asking them for an invoice and waiting more than one week, I still have no reply.
And in order to withdraw any funds, it's required to send an email to info@issuehunt.io as well.
