### ISSUE TITLE
Carousel doesn't stop dragging when releasing the button outside of the container

### ISSUE THREAD

**Issue by pierzchalatomasz** [brainhubeu/react-carousel#171]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/171)

**Describe the bug**
Carousel doesn't stop dragging when `mouseup` event is triggered outside of carousel container.

**To Reproduce**
1. Go to https://brainhubeu.github.io/react-carousel/docs/examples/simpleUsage
2. Start dragging the carousel
3. While still pressing the button move the cursor outside of carousel container
4. Release the button
5. Notice carousel is still dragging while you're not pressing the button

**Expected behavior**
Carousel should stop dragging when releasing the button (no matter if it's in the container or not).

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9852085/71660455-68aa2680-2d4b-11ea-89fb-50a4be1f2a9c.gif)

**Desktop (please complete the following information):**
 - OS: [macOS 10.14.6]
 - Browser [Chrome]
 - Version [79.0.3945.88]

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/20856232?v=4' alt='piotr-s-brainhub' width=24 height=24> piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by piotr-s-brainhub** [comment]
I checked now it's fixed.

**Comment by piotr-s-brainhub** [comment]
@sinchang 

I have a question: are you able to withdraw any funds from the issuehunt?
I ask because after writing to info@issuehunt.io, asking them for an invoice and waiting more than one week, I still have no reply.
And in order to withdraw any funds, it's required to send an email to info@issuehunt.io as well.
