### ISSUE TITLE
click to change - unable to select a photo for a low width of the screen

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#181]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2417%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/181)

**To Reproduce**
1. Open https://brainhubeu.github.io/react-carousel/docs/examples/clickToChange with Safari on iOS (iPhone) so there are three photos and the code is following:
```js
<Carousel
  clickToChange
  slidesPerPage={2}
  centered
>
 <img src={imageOne} />
 <img src={imageTwo} />
 <img src={imageThree} />
</Carousel>
```
2. Set the screen to be vertical (default for iPhone) so the screen width is very low.
3. Try to click on the most left photo.
4. It's impossible to select the most left photo.
5. Click the most right photo.
6. The most right photo occupies all the carousel.
7. So the only way to show the center photo is to drag.
8. After dragging, the center photo is shown but not fully.

**Expected behavior**
4. It should be possible to select the most left photo.
6. The most right photo should occupy most of the carousel but there should be also a space for the center photo, enabling clicking it.
7. It should be possible to show the center photo not only with dragging but also with clicking it.
8. The center photo should be shown fully, with some space for the most left and the most right photo, enabling clicking them.

No photo should be cut or shrunk horizontally.

Instead, the height of the entire carousel should be decreased when needed in order to fit always the selected image and parts of its neighbors, enabling to click them.

**Screenshots**
Video: https://drive.google.com/file/d/1gkDYx8qPymJh8PKLjNQ3UMp39n6vd_B4/view

**Smartphone (please complete the following information):**
 - Device: iPhone 5s
 - OS: iOS 12.4.4
 - Browser: Safari (AFAIK Safari version is connected with the iOS version)
 - `react-carousel`: 1.10.34

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $17.00)

- [<img src='https://avatars0.githubusercontent.com/u/20856232?v=4' alt='piotr-s-brainhub' width=24 height=24> piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($17.00)

### Submitted pull Requests
- [#464 Fixes #181](https://issuehunt.io/r/brainhubeu/react-carousel/pull/464)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by sebastiantf** [comment]
@piotr-s-brainhub Is the behaviour found in Landscape mode as seen in the Screenshot video acceptable?

**Comment by piotr-s-brainhub** [comment]
> @piotr-s-brainhub Is the behaviour found in Landscape mode as seen in the Screenshot video acceptable?

no, it's a bug
