### ISSUE TITLE
Bring back focus view on selected card

### ISSUE THREAD

**Issue by icy-meteor** [brainhubeu/react-carousel#187]
Say, that I have 8 cards, and 4 are displayed on the screen at once. When I have my 5th card selected, and if I reload my screen, it shows me the first 4 cards in view instead of the one that I had selected plus the subsequent cards.

Would be great to have this feature where the cards in current view is decided by the selected/active card.

P.S: Correct me if this feature already exists. I couldn't find it anywhere.

**Comment by piotr-s-brainhub** [comment]
@icy-meteor 

So you mean the state should be preserved after page reload?

**Comment by icy-meteor** [comment]
> @icy-meteor
> 
> So you mean the state should be preserved after page reload?

Yes, that's right. I should be able to access the cards that are currently on the view (visible to the end-user) and manipulate them so that the selected card comes on the view.

**Comment by CHaNGeTe** [comment]
Correct me if I am wrong, but I think this can be achievable via Controlled component
https://github.com/brainhubeu/react-carousel#carousel-as-controlled-element

You can set the initial value from one stored value (f.e. on localStorage)
example:
https://codesandbox.io/embed/festive-lehmann-bf9tx?fontsize=14&hidenavigation=1&theme=dark

**Comment by piotr-s-brainhub** [comment]
@CHaNGeTe 

I also think it's the right way.

**Comment by icy-meteor** [comment]
My bad, yes it is the achievable via Controlled Component.
Closed the issue.

**Comment by piotr-s-brainhub** [comment]
@icy-meteor 

I thought about saving the state into localStorage on our side but as @CHaNGeTe mentioned, thanks to the controlled component, you can handle it on its own.
Maybe in the future, we'll add an option to save into localStorage on the carousel side but only if such a feature has a high enough demand.

**Comment by piotr-s-brainhub** [comment]
@icy-meteor 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
