### ISSUE TITLE
window undefined

### ISSUE THREAD

**Issue by EmilEriksen** [brainhubeu/react-carousel#192]
Ever since version 1.10.37 (probably .36) I'm getting a window undefined error. .35 works fine. I'm using Next JS so my app is SSR. Unfortunately I can't figure out what causes the error only that in version .37 the start of `lib/react-carousel.js` looks like this (note the use of `window`)
```
!function (e, t) {
    'object' == typeof exports && 'object' == typeof module ? module.exports = t(require('react')) : 'function' == typeof define && define.amd ? define('react-carousel', ['react'], t) : 'object' == typeof exports ? exports['react-carousel'] = t(require('react')) : e['react-carousel'] = t(e.React)
}(window, (function (e) {
...
```
and in .35 it looks like this
```
!function (e, t) {
    'object' == typeof exports && 'object' == typeof module ? module.exports = t(require('react')) : 'function' == typeof define && define.amd ? define('react-carousel', ['react'], t) : 'object' == typeof exports ? exports['react-carousel'] = t(require('react')) : e['react-carousel'] = t(e.React)
}('undefined' != typeof self ? self : this, function (e) {
...
```

**Comment by klendi** [comment]
yeah got this also. Any fix ?

**Comment by piotr-s-brainhub** [comment]
@EmilEriksen @klendi 

We're working on it.
The easiest fix for now seems to be using a previous version.

**Comment by klendi** [comment]
I used version ^1.10.34 and it works now.

**Comment by piotr-s-brainhub** [comment]
@EmilEriksen @klendi 

I checked out this commit https://github.com/brainhubeu/react-carousel/commit/9764a17e37632fec5c342969d1db9d0f26c41d44 (1.10.34), reinstalled `node_moduls`, both in root and `docs-www`, tried `./tools/deploy-gh-pages.sh` and I get `WebpackError: window is not defined` error.

I also tried cloning the repo from scratch, checking out that commit etc. and I see the same error.

**Comment by piotr-s-brainhub** [comment]
it also fails for https://github.com/brainhubeu/react-carousel/commit/6ccceb93ce06877d4806f1dc33c63c32c7f6540d which had a successful gh pages publishing job in the past

**Comment by piotr-s-brainhub** [comment]
I also switched to Node.js 10.17.0 to have the same version as in https://circleci.com/gh/brainhubeu/react-carousel/1288 which has passed

**Comment by piotr-s-brainhub** [comment]
Though when I run `yarn add @brainhubeu/react-carousel` and I type `require('@brainhubeu/react-carousel')` in the Node.js console, it passes for 1.10.34 and 1.10.35 but it fails for 1.10.36 and 1.10.37.

**Comment by piotr-s-brainhub** [comment]
@EmilEriksen @klendi 
it's fixed in @brainhubeu/react-carousel@1.10.39 (published manually)

**Comment by piotr-s-brainhub** [comment]
```
⟩ yarn add @brainhubeu/react-carousel
yarn add v1.16.0
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-router@4.3.1" has unmet peer dependency "react@>=15".
warning " > eslint-config-airbnb-base@13.1.0" has incorrect peer dependency "eslint@^4.19.1 || ^5.3.0".
warning " > eslint-plugin-import@2.17.2" has incorrect peer dependency "eslint@2.x - 5.x".
warning " > react-native@0.59.5" has unmet peer dependency "react@16.8.3".
warning "react-native > metro-react-native-babel-transformer@0.51.0" has unmet peer dependency "@babel/core@*".
warning "react-native > @react-native-community/cli > metro-react-native-babel-transformer@0.51.1" has unmet peer dependency "@babel/core@*".
warning " > @brainhubeu/react-carousel@1.10.48" has unmet peer dependency "react@>0.14.0 || >15.0.0".
warning " > @brainhubeu/react-carousel@1.10.48" has unmet peer dependency "react-dom@>0.14.0 || >15.0.0".
[4/4] 🔨  Building fresh packages...
warning No license field
success Saved 1 new dependency.
info Direct dependencies
└─ @brainhubeu/react-carousel@1.10.48
info All dependencies
└─ @brainhubeu/react-carousel@1.10.48
✨  Done in 14.22s.

[piotr.sroczkowski@MacBook-Pro-user-2.local 16:19:22] ~
⟩ node
> require('@brainhubeu/react-carousel/lib/react-carousel')
{ Dots: [Function: t], default: [Function: t] }
> require('@brainhubeu/react-carousel')
{ Dots: [Function: t], default: [Function: t] }
>
```

I checked it's fixed for the newest version (@brainhubeu/react-carousel@1.10.48 - published automatically).

**Comment by piotr-s-brainhub** [comment]
@EmilEriksen @klendi 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by slmr** [comment]
Try dynamic import: 
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr
