### ISSUE TITLE
ability to connect local demo with local carousel code and hot reloading

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#194]
Currently, I have to modify `react-carousel` source code, publish it and update `react-carousel` version in the demo app (`docs-www` directory).

Therefore, in order to develop `react-carousel` smoothly, I need demo to be updated with hot reload after any `react-carousel` source code modification.
Hot reloading isn't essential, it could possibly work with server rerunning and page reload but definitively I don't want to publish and install `react-carousel` for each change.

**Comment by CHaNGeTe** [comment]
Can `npm link` help with this?

**Comment by piotr-s-brainhub** [comment]
@CHaNGeTe 

I don't think `npm link` is right here because there's a different file structure in the build bundle.

Anyway, there's already an opened PR for this issue.
