### ISSUE TITLE
Proper documentation for regression tests

### ISSUE THREAD

**Issue by CHaNGeTe** [brainhubeu/react-carousel#196]
**Describe the bug**
Regression tests documentation is obsolete
https://github.com/brainhubeu/react-carousel#regression-tests

It referes to `npm run example` which was removed from package.json on https://github.com/brainhubeu/react-carousel/commit/b2759a3990682e76a8bb17ee5c6d838d85ff37ff#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L16

**Expected behavior**
Proper documentation for regression tests

**Comment by piotr-s-brainhub** [comment]
Thanks @CHaNGeTe 

We have some problems with our regression tests but we plan to fix and improve them.

**Comment by piotr-s-brainhub** [comment]
@CHaNGeTe 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by piotr-s-brainhub** [comment]
@RobertHebel 

I checked the `yarn test:e2e` command which is now in README works locally so I close this issue.
<img width="748" alt="Screenshot 2020-03-17 at 13 17 25" src="https://user-images.githubusercontent.com/20856232/76855616-c5e54c80-6851-11ea-806a-0480c454c4a9.png">
