### ISSUE TITLE
Turn Off Console Debugging

### ISSUE THREAD

**Issue by Lagicrus** [brainhubeu/react-carousel#235]
**Describe the solution you'd like**
A way to disable the mouse events being logged to console. Such as the "onMouseDown check"

I had thought it was just a me thing or because it had yet to be built. But then I saw it on the live site which makes me confused why you want constant logging on the live version of your product with no way to disable it.

**Comment by piotr-s-brainhub** [comment]
@Lagicrus 

Thanks for reporting.
Could you review https://github.com/brainhubeu/react-carousel/pull/236 ?
Excluding the building scripts, the only other file with debugging code is https://github.com/brainhubeu/react-carousel/blob/master/docs-www/src/globalReferences.js which is used in demo.

**Comment by Lagicrus** [comment]
Hey @piotr-s-brainhub , that looks to be it. Thanks :)
![image](https://user-images.githubusercontent.com/24227350/73901144-cfaa8600-4889-11ea-8685-f3fb7447f0d1.png)
was what I was getting

**Comment by piotr-s-brainhub** [comment]
@Lagicrus so https://github.com/brainhubeu/react-carousel/pull/236 should be enough - could you review?

**Comment by Lagicrus** [comment]
Added an approval review

**Comment by piotr-s-brainhub** [comment]
@Lagicrus 

Thanks, the fix should be in 1.10.56 version

**Comment by piotr-s-brainhub** [comment]
@Lagicrus 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
