### ISSUE TITLE
Can you please make available as a CDN?? 

### ISSUE THREAD

**Issue by JustinStoddard** [brainhubeu/react-carousel#240]
**Is your feature request related to a problem? Please describe.**
My team, because of some limitations of legacy code, need to use React and other libraries through their CDN links. We also need a slick slider. We use them frequently. And the solution has been our own "made from scratch" slider. It works well but doesn't have infinite scroll :(

**Describe the solution you'd like**
I've love to be able to use a CDN and stop the headaches of animating and programming our own slick slider.

**Describe alternatives you've considered**
We've tried to use React-Slick but that package uses Webpack. And we don't, so we cant use it.

**Additional context**

**Comment by piotr-s-brainhub** [comment]
@JustinStoddard 

Could you explain what CDN means in context of a carousel library?

You use React but don't use Webpack?

**Comment by JustinStoddard** [comment]
@piotr-s-brainhub Yes! The situation is a bit odd because of legacy code. By CDN I mean a way to import the components into the project using a <script> tag in the root html file instead of as an npm package. So for example. We use the React production CDN. So when I want to use a `useState` I have to write it out as 
`const [myVar, setMyVar] = React.useState(0);`. We also use Material-UI. So when I want to use their typography comp we have to write it out as `<MaterialUI.Typography />`. So ideally, it would be nice to grab the components from this library the same way. Does this make sense? Again this is because of some legacy code. We're trying to transition and using CDN's is kind of the first step. The software is a site builder that uses a dated templating system.

**Comment by piotr-s-brainhub** [comment]
@JustinStoddard 

can you install manually `@brainhubeu/react-carousel` from npm or yarn and attach the files from the `~/node_modules/@brainhubeu/react-carousel/lib/` directory?

**Comment by JustinStoddard** [comment]
@piotr-s-brainhub I had a conversation with some other developers about our publishing process. I guess we don't load npm modules into each of our sites. So we would need a CDN.

**Comment by piotr-s-brainhub** [comment]
@JustinStoddard 

you can use these links:
https://unpkg.com/@brainhubeu/react-carousel@1.10.56/lib/react-carousel.js
https://unpkg.com/@brainhubeu/react-carousel@1.10.56/lib/style.css

**Comment by JustinStoddard** [comment]
@piotr-s-brainhub You are the man!!!!

**Comment by piotr-s-brainhub** [comment]
@JustinStoddard 

so I close this issue.

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by JustinStoddard** [comment]
@piotr-s-brainhub  I would be glad to!

**Comment by JustinStoddard** [comment]
@piotr-s-brainhub One more question for you. What is the name of the variable it exposes to the document? Can I just call the `Carousel` component. Or do I need to call a parent class first? Like so: `<ReactCarousel.Carousel />`

**Comment by piotr-s-brainhub** [comment]
@JustinStoddard 

I'm not sure if that link is possible to be used.
I get
```
Uncaught TypeError: Cannot read property 'PureComponent' of undefined
    at Object.<anonymous> (react-carousel.js:19)
    at t (react-carousel.js:1)
    at Object.<anonymous> (react-carousel.js:19)
    at t (react-carousel.js:1)
    at Object.<anonymous> (react-carousel.js:6)
    at t (react-carousel.js:1)
    at Object.<anonymous> (react-carousel.js:6)
    at t (react-carousel.js:1)
    at react-carousel.js:1
    at react-carousel.js:1
```

**Comment by piotr-s-brainhub** [comment]
Though I fixed that error, adding React CDN links https://reactjs.org/docs/cdn-links.html

**Comment by piotr-s-brainhub** [comment]
Anyway I'm not able to find any exported global react carousel variable.

**Comment by JustinStoddard** [comment]
@piotr-s-brainhub 

This is the link i've been trying to use .
`<script crossorigin type="text/javascript" src="https://unpkg.com/@brainhubeu/react-carousel@1.10.56/lib/react-carousel.js"></script>`

**Comment by JustinStoddard** [comment]
Is it possible to have it export a global variable?

**Comment by JustinStoddard** [comment]
@piotr-s-brainhub 

This is from Material-UI's CDN

```!function(e, t) {
    "object" == typeof exports && "undefined" != typeof module ? t(exports, require("react"), require("react-dom")) : "function" == typeof define && define.amd ? define(["exports", "react", "react-dom"], t) : t((e = e || self).MaterialUI = {}, e.React, e.ReactDOM)
}```

The global variable they export is `MaterialUI`

**Comment by piotr-s-brainhub** [comment]
@JustinStoddard 

you can use:
- BrainhubeuReactCarousel
- BrainhubeuReactCarouselDots
- BrainhubeuReactCarouselItem
- BrainhubeuReactCarouselWrapper

these global variables are available in the alpha version ( https://unpkg.com/@brainhubeu/react-carousel@1.10.57-alpha/lib/react-carousel.js )

**Comment by JustinStoddard** [comment]
@piotr-s-brainhub You are a wonderful person! Thank you!

**Comment by JustinStoddard** [comment]
@piotr-s-brainhub

Hello again. Two questions for you. 1, is the CSS link compatible with the new JS CDN and 2, does your library work with React v16.8+ (With React Hooks)

**Comment by piotr-s-brainhub** [comment]
@JustinStoddard 

1) CSS should be compatible with JS for the same `@brainhubeu/react-carousel` version
2) There's no guarantee to work with react@16 because `@brainhubeu/react-carousel` is still using  react@15

**Comment by piotr-s-brainhub** [comment]
@JustinStoddard 

as it's written now in README, globals are available only in the `-cdn` version (each release publishes both the standard version and a CDN version) so the latest one is now `1.11.0-cdn`
