### ISSUE TITLE
Please width on props

### ISSUE THREAD

**Issue by lostspirit1** [brainhubeu/react-carousel#254]
It’s a little complicated to manipulate the width with the styled components

would have how to put width by props?

**Comment by piotr-s-brainhub** [comment]
@lostspirit1 

you'd like to be able to set width of the carousel component?

**Comment by lostspirit1** [comment]
yes I'm having a lot of trouble defining the width of the carousel, even with a container in it:
but I can't define that it takes the height and width 100% of my grid container:

![image](https://user-images.githubusercontent.com/38575233/74202029-17def500-4c4a-11ea-98ba-f48dfa7e7bb7.png)


code:
```
const News2_0Carousel = () => {
  return (
    <Styled.News2Wrap background={TestBG2}>
      <div style={{width:'100%'}}>
      <Carousel arrows slidesPerPage={1}> 
      <div>a</div>
      </Carousel>  
      </div>
      <div>
        h
      </div>
      <div>
  c
      </div>
      <div>
      d  
      </div>
    </Styled.News2Wrap>
  );
};

```

css in js:

```
const News2Wrap = styled.div`
  display: grid;
  grid-template-columns: 18% auto auto auto;
  grid-template-rows: 1fr 1fr;
  grid-column-gap: 2px;
  grid-row-gap: 2px;
  height: 52vh;
  margin-top: 40px;
  & > div:nth-child(1) {
    grid-area: 1 / 1 / 3 / 3;
    background-color: blue;
    background-size: cover;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-position: center;
  }
  & > div:nth-child(2) {
    display:flex;
    align-items:center;
    grid-area: 1 / 3 / 2 / 5;
    background-color: rgb(255, 0, 0);
    padding: 20px;

  }
  & > div:nth-child(3) {
    display:flex;
    align-items:center;
    grid-area: 2 / 3 / 3 / 4;
    background-color: rgb(255, 127, 0);
    padding: 20px;

  }
  & > div:nth-child(4) {
    display:flex;
    align-items:center;
    grid-area: 2 / 4 / 3 / 5;
    background-color: rgb(255, 255, 0);
    padding: 20px;

`;
```

**Comment by lostspirit1** [comment]
I realized that the problem is in the li:

![image](https://user-images.githubusercontent.com/38575233/74203461-7312e680-4c4e-11ea-874f-c8af9f01c17c.png)


![image](https://user-images.githubusercontent.com/38575233/74203472-7ad28b00-4c4e-11ea-9457-5a3694968399.png)

**Comment by piotr-s-brainhub** [comment]
@lostspirit1 

so do you need anything on the `@brainhubeu/react-carousel` side?

**Comment by piotr-s-brainhub** [comment]
@lostspirit1 

As there's no reply, I close this issue but you can reopen it when needed.

**Comment by Thanhtung1998** [comment]
I am newbie and i am using your carousel library i found out when turning page your component is warning memory lake how can i fix this
