### ISSUE TITLE
get caroussel item on center

### ISSUE THREAD

**Issue by sptGabriel** [brainhubeu/react-carousel#257]
Hello I would like to know how to get the centered item caroussel to apply different styles?

**Comment by piotr-s-brainhub** [comment]
@sptGabriel 

I don't clearly understand what you mean.

Here https://beghp.github.io/gh-pages-rc-4/docs/examples/centered you have an example of a centered carousel.
If you want to have a custom style, you can write proper CSS.

**Comment by sptGabriel** [comment]
Hello I'm having trouble finding the css class of the item in the center

**Comment by piotr-s-brainhub** [comment]
@sptGabriel 

each carousel item should have `BrainhubCarouselItem` class

**Comment by piotr-s-brainhub** [comment]
@sptGabriel 

does it resolve your issue?

**Comment by piotr-s-brainhub** [comment]
@sptGabriel 

I close this issue as you don't reply but please feel free to reopen it if you need any more help.
