### ISSUE TITLE
Do not render CarrouselItem if no `this.props.children`

### ISSUE THREAD

**Issue by seedwalk** [brainhubeu/react-carousel#258]
Hello there, 

I am encountering an issue with the carouselItem,

my code looks more or less like this :

```
 <Carousel>
 {props.evaluateSomething1 ? (
          <div>1</div>)}
 {props.evaluateSomething2 ? (
          <div>2</div>)}
 {props.evaluateSomething1 3 (
          <div>3</div>)}
</Carousel>
```

Whenever, `evaluateSometing` returns false, the content for the item does not get rendered. However, the Carousel item does get rendered. Which ends up in empty spaces within the carrousel.

So, in carrousel item, if props.children do not exist Carousel Item should not render or return null

I've pulled the repo, and tried to create a pr but 
```
 git push --set-upstream origin DoNotRenderItemIfNoChildren
ERROR: Permission to brainhubeu/react-carousel.git denied to seedwalk.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Could you please fix this one for me. it should be a quick fix.

Looking for to it, thanks in advance

**Comment by piotr-s-brainhub** [comment]
@seedwalk 

Thanks for reporting.
The PR should be opened from a fork.

**Comment by seedwalk** [comment]
@piotr-s-brainhub 
https://github.com/brainhubeu/react-carousel/pull/259
