### ISSUE TITLE
arrows - for the last item, carousel jumps instead of animate

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#263]
**To Reproduce**
1) open https://brainhubeu.github.io/react-carousel/docs/examples/defaultArrows
2) click the right arrow until you go to the last item
3) before reaching the last item, the items are animated
4) the last item appears immediately without any animation
5) click the left arrow until you go to the first item
6) before reaching the first item, the items are animated
7) the first item appears immediately without any animation

Instead of the default 3 items, you can also use these:
```
<Carousel
  arrows
>
  <div>item-1</div>
  <div>item-2</div>
  <div>item-3</div>
  <div>item-4</div>
  <div>item-5</div>
  <div>item-6</div>
  <div>item-7</div>
</Carousel>

```

**Expected behavior**
4) the last item should be animated
7) the first item should be animated

**Videos**
https://recordit.co/w70GCv8Bm4
https://recordit.co/VFLCn48n1n

**Desktop
 - OS: Mac OS X 10.14.6
 - Browser: Chrome 80.0.3987.100
 - Version: 1.10.64

**Comment by lwjameson** [comment]
I see there is a fix for this in Review.  Would love to see that merged and released soon.  I have replaced react-slick in one of my projects with this component and this is the only issue I currently have.  Nice job.

**Comment by curt-tophatter** [comment]
fwiw I was able to get around this by being explicit in the widths of each slide.
