### ISSUE TITLE
Add information about styles to docs

### ISSUE THREAD

**Issue by PsychoXIVI** [brainhubeu/react-carousel#266]
There is no information in Docs that I need to import styles too. I found it after a while on Github page, but it would be much easier and faster to get it right on docs.

```typescript
import '@brainhubeu/react-carousel/lib/style.css';
```

Please add it at:
https://brainhubeu.github.io/react-carousel/docs/gettingStarted

Or, maybe it could be added inside Typescript typings package?

In such case this import
```typescript
import Carousel from '@brainhubeu/react-carousel';
```
could work nicely.

**Comment by piotr-s-brainhub** [comment]
@PsychoXIVI 

Thanks for reporting.
I just opened a PR and I'm waiting for a review from another maintainer.
