### ISSUE TITLE
IE11 error

### ISSUE THREAD

**Issue by dviry** [brainhubeu/react-carousel#305]
IE11 shows absolutely nothing (https://brainhubeu.github.io/react-carousel/docs/examples/multipleItems) and shows following in the Error Console:

Unhandled promise rejection TypeError: Object doesn't support property or method 'endsWith'

I guess it's missing some polyfill(s)...

Thanks

**Comment by piotr-s-brainhub** [comment]
@dviry 

Thanks for reporting.
Maybe we'll fix that but if you want, you're more than welcome to open a PR.

It looks to be strange because:
- `react-carousel` source code doesn't contain any `endsWith`
- `Object` doesn't have `endsWith` method
so maybe one of the `react-carousel` dependencies uses an object in IE11 instead of a string.

**Comment by piotr-s-brainhub** [comment]
Unfortunately, I don't have IE11 but I'm able to reproduce this error with https://ie10.ieonchrome.com/#https://brainhubeu.github.io/react-carousel/docs/examples/multipleItems

**Comment by piotr-s-brainhub** [comment]
I managed to run IE11 in VirtualBox so there I see a blank page with the `Object doesn't support property or method 'endsWith'` error.
<img width="554" alt="Screenshot 2020-03-05 at 21 22 01" src="https://user-images.githubusercontent.com/20856232/76022532-a1bb6e80-5f27-11ea-9a36-4604dc680868.png">
a video: https://recordit.co/OHTfv0dXNF

On the hand, the simulator (https://ie10.ieonchrome.com/#https://brainhubeu.github.io/react-carousel/docs/examples/multipleItems) shows menu and the `Multiple items You can show more than one item per page, using slidesPerPage prop.` text
<img width="1401" alt="Screenshot 2020-03-05 at 21 23 09" src="https://user-images.githubusercontent.com/20856232/76022737-04146f00-5f28-11ea-8df6-88d59dcba4d3.png">

**Comment by RobertHebel** [comment]
React-carousel docs now work on ie browsers 🎉
