### ISSUE TITLE
Setting width and offset

### ISSUE THREAD

**Issue by Lukasz-pluszczewski** [brainhubeu/react-carousel#31]
Add an option to set width of an element (disabling default calculating width from carousel width and number of visible elements) and offset between them. 
Things to consider:
- Should offset be aways visible or first's left and last's offsets should be offscreen (maybe another prop to control it?
- Can offset be turned on without setting width (I think yes, I don't see any possible issues with it. Are there any?)

**Comment by Robert-brainhub** [comment]
Added in https://github.com/brainhubeu/react-carousel/pull/38 and https://github.com/brainhubeu/react-carousel/pull/39
