### ISSUE TITLE
zooming slides

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#318]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/318)

`zoom` option passed to the `Carousel` component with the following values:
- `null` (default) - no zoom
- `on hover` - zoom the slide in on hover, zoom out when the hover is off
- `on click` - zoom the slide in after clicking it, zoom it out after clicking it again
- `on double click` - zoom the slide in after double-clicking it, zoom it out after double-clicking it again

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by piotr-s-brainhub** [comment]
@keval77

I see you've requested a bounty of 40 USD on IssueHunt.

Could you implement it for a total of 20 USD?

**Comment by RobertHebel** [comment]
We don't have plans to add new features in carousel v1. In carousel v2 you can implement requested behavior by creating your own custom plugin https://brainhubeu.github.io/react-carousel/docs/plugins/creatingCustomPlugins
