### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#319]
`pagination` option passed to the `Carousel` component, it's an object with the following fields:
- `mode` (String)
  - `slide` - the logical page number corresponds to the first fully visible slide number
  - `page` - the logical page number is incremented after replacing the visible images into a set of next images
- `input` (Boolean) - if set to `true`, there's an input to control the carousel, between the buttons moving to next and previous page
- `position` (String) - where the pagination component is placed:
  - `bottom`
  - `left`
  - `right`
  - `top`
- `nextButtonText` (String, default `>`) - the text placed on the button moving to the next page
- `previousButtonText` (String, default `<`) - the text placed on the button moving to the previous page
- `endButtonText` (String, default `>>`) - the text placed on the button moving to the last page
- `startButtonText` (String, default `<<`) - the text placed on the button moving to the first page

**Comment by RobertHebel** [comment]
sorry @piotr-s-brainhub but we don't have plans to introduce this feature to carousel v1
