### ISSUE TITLE
pausing auto-animation buttons

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#321]
It depends on #320.

`pausingButtons` option passed to the `Carousel` component, it's an object with the following fields:
- `position` (String) - where the pausing component is placed:
  - `bottom`
  - `left`
  - `right`
  - `top`
- `stopButtonText` (String, default `⏸`) - the text placed on the button stoping the animation
- `startButtonText` (String, default `▶️`) - the text placed on the button starting the animation
- `multipleButtons` (Boolean, default `true`) - if it's set to `true`, it displays two buttons: one to stop animation, another to start so one of the buttons is always disabled; if it's set to `false`, it shows only one button with changing text

**Comment by RobertHebel** [comment]
Closing because #320 is closed
