### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#324]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/324)

A progress bar showing slides progress.
`progressBar` option passed to the `Carousel` component, it's an object with the following fields:
- `position` (String) - where the progress bar component is placed:
  - `bottom`
  - `left`
  - `right`
  - `top`
- `lengthInPercent` (Number) - the length relative to the carousel length in percent
- `widthInPx` (Number) - the width in `px`

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by piotr-s-brainhub** [comment]
@rohitgupta200305 

I see you've requested a bounty of 40 USD for fixing this issue on IssueHunt. Would 20 USD work for you so there would be 22 USD for fixing this issue (2 + 20) minus the IssueHunt fee?

**Comment by RobertHebel** [comment]
You can achieve this behavior in a controlled carousel component. You can get the percentage by dividing the current value by the total number of slides. That's why I think we don't need to introduce it as a separate feature.
