### ISSUE TITLE
an alternate slide on hover

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#325]
`AlternateImage` component with the following options:
- `default` (Component) - a slide shown as default
- `onHover` (Component) - a slide shown on hover

It could be used to obtain a similar effect as in https://brainhub.eu/about-us/

**Comment by Lukasz-pluszczewski** [comment]
It's useful feature, but I'm wondering if that's what should be implemented in the carousel itself as this would complicate it's API. The feature can be implemented in slides themselves.

**Comment by RobertHebel** [comment]
As @Lukasz-pluszczewski  there is no need to complicate our API when you can implement this feature in your slide component
