### ISSUE TITLE
text box

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#326]
`textBox` option passed to the `CarouselItem` component, it's an object with the following fields:
- `text` (String) - text displayed on the slide
- `top` (Number, default `60`) - relative top edge of the text box as the percent of slide height
- `bottom` (Number, default `90`) - relative bottom edge of the text box as the percent of slide height
- `left` (Number, default `10`) - relative left edge of the text box as the percent of slide width
- `right` (Number, default `90`) - relative right edge of the text box as the percent of slide width
- `when` (String, default `always`) - when the text box is shown:
  - `always`
  - `on hover`
  - `on click` - a click shows the text box and the next click hides it
  - `on double click` - a double-click shows the text box and the next double-click hides it
- `color` (Number, default `black`) - the text color of the text box, either name or in `#a0a0a0` format or in `#aaa` format
- `backgroundColor` (Number, default `black`) - the background color of the text box, either name or in `#a0a0a0` format or in `#aaa` format
- `transparency` (Number, default `0`) - transparency in percent

**Comment by RobertHebel** [comment]
We don't have plans to add new features in carousel v1. In carousel v2 you can implement requested behavior by creating your own custom plugin https://brainhubeu.github.io/react-carousel/docs/plugins/creatingCustomPlugins
