### ISSUE TITLE
categories

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#327]
When the carousel is horizontal, I can:
- swipe slides within the same category, dragging horizontally or clicking on horizontal arrows
- switch category, dragging vertically or clicking on vertical arrows

and vice versa if the carousel is vertical.

There's a `CarouselItemCategory` component allowing grouping slides into categories.

**Comment by Lukasz-pluszczewski** [comment]
You can achieve that with just a carousel of carousels (the only thing needed is adding a "vertical" prop)

**Comment by piotr-s-brainhub** [comment]
so let's wait until #162 is finished, then we'll check whether it works correctly with a carousel of carousels (theoretically it should work but even if both the horizontal and the vertical carousels are tested, there can occur a bug breaking a carousel of carousels)

**Comment by RobertHebel** [comment]
> so let's wait until #162 is finished, then we'll check whether it works correctly with a carousel of carousels (theoretically it should work but even if both the horizontal and the vertical carousels are tested, there can occur a bug breaking a carousel of carousels)

If it won't work when the vertical plugin will be implemented please reopen this issue. Closing for now
