### ISSUE TITLE
double arrows

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#328]
One arrow moves one slide while another replaces all the visible page of slides into another page.

`doubleArrows` option (Boolean, default `false`) passed to the Carousel component

**Comment by RobertHebel** [comment]
We don't have plans to add new features in carousel v1. In carousel v2 you can implement requested behavior by creating your own custom plugin https://brainhubeu.github.io/react-carousel/docs/plugins/creatingCustomPlugins
