### ISSUE TITLE
removing images from the list

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#329]
If the carousel is horizontal, swiping an image vertically (either up or down) removes it from the list.
If the carousel is vertical, swiping an image horizontally (either left or right) removes it from the list.
In order to reset the list, reload the page.

`removableSlides` (Boolean, default `false`) option passed to the Carousel component.
`reset` (Boolean, default `false`), option passed to the Carousel component - changing its value to `true`, resets the slides and the carousel itself changes this value back to `false`

**Comment by Lukasz-pluszczewski** [comment]
It can just be achieved by adding a swipe event handler to slides and handle the removing of the slides outside of the carousel. Adding this feature would require adding onRemove prop and allowing the developer to handle removing slides outside anyway.

**Comment by piotr-s-brainhub** [comment]
IMO this is a useful feature but its value is low and probably it's already possible with some code written by a carousel user

**Comment by RobertHebel** [comment]
I agree with @Lukasz-pluszczewski. Closing
