### ISSUE TITLE
Dots component does not account for large values in case of infinite carousel

### ISSUE THREAD

**Issue by Lukasz-pluszczewski** [brainhubeu/react-carousel#33]
When infinite option is turned on, dots will scroll to indexes 0-n (where n is index of last element). When current index is very large (in case of autoplay value is being incremented so it can be any large number) clicking on dot or thumbnail will make carousel animate through all those values instead of to the nearest one.

I see two solutions:
1. Just calculate nearest one in Dots component
2. Make mechanism to reset value in case of infinite (can be tricky as this is controlled component: triggering onChange, will in turn trigger state change and Carousel will have difficult time figuring out if the change was just it's resetting mechanism and animation is unnecessary or it's triggered from outside and we should animate)

**Comment by Robert-brainhub** [comment]
Fixed in https://github.com/brainhubeu/react-carousel/pull/46
