### ISSUE TITLE
the central image is the largest 

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#330]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/330)

The central image is the largest and the more distant from the center is an image, the smaller it is.

`decreaseImageSizeOutOfCenterRatio` (Number, default `1`) option passed to the Carousel component - each next image, starting from the central image to both directions, has the size multiplied by this value; if the ratio is less than 1, the central image is the largest but if it's more than 1, the central image is the smallest

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by Lukasz-pluszczewski** [comment]
See my objections to modifying the behaviour of "central" slide: https://github.com/brainhubeu/react-carousel/issues/331#issuecomment-598100663

**Comment by RobertHebel** [comment]
@piotr-s-brainhub sorry we decided we won't implement this feature
