### ISSUE TITLE
white-black

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#331]
`whiteBlack` option passed to the Carousel component, it's an object with the following fields:
- `hover`:
  - `null` - default - all the images are colorful
  - `on`: - the image on hover is white-black while the others are colorful
  - `off` - the image on hover is colorful while the others are white-black
- `central`:
  - `null` - default - all the images are colorful
  - `on`: - the central image is white-black while the others are colorful
  - `off` - the central image is colorful while the others are white-black
- `visible`
  - `null` - default - all the images are colorful
  - `on`: - all the fully visible images are white-black while the partially visible ones are colorful
  - `off` - all the fully visible images are colorful while the partially visible ones are white-black
- `thumbnails` (Boolean, default `false`) - if set to `true`, the thumbnails are `white-black`
- `whiteBlackWins` (Boolean, default `false`) - if any rules, telling whether the given image should be white-black or colorful, contradict each other, this rule specifies whether the image should be white-black

**Comment by Lukasz-pluszczewski** [comment]
The issue with "central" prop, in this and other feature proposals, is that there is no central slide in some cases: with `centered=false` and `slidesPerPage=1`.
It would make more sense to call it "current" although, it's still problematic in case of `centered=false` and `slidesPerPage > 1`.

**Comment by piotr-s-brainhub** [comment]
@Lukasz-pluszczewski 

so maybe the `central` option would be available only for `centered=false`

**Comment by RobertHebel** [comment]
@piotr-s-brainhub Sorry, we decided we won't have this feature in react-carousel
