### ISSUE TITLE
if images are partially transparent, allow their rectangles to infiltrate each other

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#332]
If an image is partially transparent, the colorful part may have various shapes.
No infiltration (default):
<img width="869" alt="Screenshot 2020-03-11 at 18 37 54" src="https://user-images.githubusercontent.com/20856232/76446506-73c2a800-63c7-11ea-9db2-c7eba62baf93.png">

Infiltration:
<img width="548" alt="Screenshot 2020-03-11 at 18 42 23" src="https://user-images.githubusercontent.com/20856232/76446923-14b16300-63c8-11ea-8da0-06607e7b9fbf.png">

`infiltrate` option (Boolean, default `false`) passed to the Carousel component

**Comment by RobertHebel** [comment]
sorry @piotr-s-brainhub we decided we won't implement this feature
