### ISSUE TITLE
snake carousel

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#333]
<img width="888" alt="Screenshot 2020-03-11 at 19 05 22" src="https://user-images.githubusercontent.com/20856232/76448842-4d067080-63cb-11ea-9a5f-420b9a5ffa24.png">

`snake` option passed to the Carousel component being an object with the following fields:
- `unit`:
  - `px`
  - `slides`
- `chain` (String) in the following format: `7R3D7L4D3R2U2R2D2R2U2R`, numbers are chain lengths in the specified unit, `U` means up, `D` means down, `L` means left, `R` means right, the passed direction is the direction of slides movement (for animation or when clicking the next arrow)
- `isNextOver` (Boolean, default `true`) - when one slide covers another, this option specifies which slides is over, covering another slide, next means the slide which was at the starting place more recently

**Comment by RobertHebel** [comment]
sorry, @piotr-s-brainhub we decided we won't have this feature in react-carousel
