### ISSUE TITLE
uploading new images

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#334]
`imageUpload` option passed to the `Carousel` component, it's an object with the following fields:
- `position` (String) - where the image upload component is placed:
  - `bottom`
  - `left`
  - `right`
  - `top`

Uploading new images appends them to the carousel which could be either used as a fancy effect or to upload them to the server.

**Comment by RobertHebel** [comment]
IMO uploading files should be handled by other components than react-carousel. Closing.
