### ISSUE TITLE
voting for images

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#335]
`voting` (String, default `''`) option passed to the Carousel component, it's an object containing the following fields:
- `options` (String, default `👎👍`) string being a chain of available votes as icons
- `swipeLeftOption` (String, default `👎`) - the vote when swiping left; no vote is made if it's `null`
- `swipeRightOption` (String, default `👍`) - the vote when swiping right; no vote is made if it's `null`
- `swipeUpOption` (String, default `null`) - the vote when swiping up; no vote is made if it's `null`
- `swipeDownOption` (String, default `null`) - the vote when swiping down; no vote is made if it's `null`
- `votingBoxHeight` (Number, default `20`) - voting box height as percent of the carousel height
- `votingBoxTop`  (Number, default `70`) - voting box top position as percent of the carousel height

The voting box component is always centered.

**Comment by RobertHebel** [comment]
Sorry @piotr-s-brainhub we don't have plans to implement this feature
