### ISSUE TITLE
Separate logic from UI with headless component

### ISSUE THREAD

**Issue by jaworek** [brainhubeu/react-carousel#339]
**Is your feature request related to a problem? Please describe.**
I have used this library in my project. One of the main issues with this library, as well as other libraries for creating carousels is customisability. It is also hard to customise look of the component as it often requires overwriting provided CSS styles.Some of them had one feature and other had different feature which was needed.

**Describe the solution you'd like**
I noticed that more and more libraries for React create headless components that do not provide UI and have great composability and extensibility.
I think it would really benefit if logic of this library was extracted to "core".
This would allow users make their own extensions without relaying on implementation from package creators and if some extension is popular enough it could be added as a built-in plugin.

**Describe alternatives you've considered**
So far I was not able to find such library, which made me create custom implementations when I needed fine grained control.

**Additional context**
Articles and links to repositories with headless components that inspired me to make this post:
- https://www.merrickchristensen.com/articles/headless-user-interface-components/
- https://kentcdodds.com/blog/inversion-of-control
- https://reacttraining.com/reach-ui/
- https://github.com/downshift-js/downshift
- https://github.com/tannerlinsley/react-table
- https://github.com/tannerlinsley/react-form
- https://github.com/tannerlinsley/react-charts

I understand that this request might be a bit out of scope for this project. I hope this feedback will give ideas for the future or separate implementation when possible.

**Comment by piotr-s-brainhub** [comment]
@jaworek 

Thanks for your suggestion.
I guess we have to provide some default children with the ability to replace them.

**Comment by jaworek** [comment]
As an example I had a project that required me to provide only right arrow. I was able to achieve it by hiding it with CSS, but this still required me to give placeholder function for left arrow.
Having option to make custom implementation would allow me to make something more tailored for my needs.

**Comment by piotr-s-brainhub** [comment]
@jaworek 

do you think creating a headless component requires only replacing the hardcoded part in the `render` method by general `this.props.children(`?

**Comment by jaworek** [comment]
I think it should be possible. API could be similar to `Dots`.  From what I see it is now possible to do custom component with dots. It is just not documented. Other part of carousel could be done in similar manner. And parent component could provide basic functionality using render props.

**Comment by jaworek** [comment]
Another solution could be similar to what `react-router`. Container component could have all necessary state and it would be accessible using hooks and context to keep everything in sync. I think this would make it a bit more flexible and easier to understand compared to render props.

**Comment by piotr-s-brainhub** [comment]
@jaworek 

Thanks for your suggestions.

@RobertHebel is working on it.

**Comment by jaworek** [comment]
Great! I'm glad my idea helped :D

**Comment by piotr-s-brainhub** [comment]
@jaworek 

you're welcome

**Comment by RobertHebel** [comment]
@jaworek I've created a PR with carousel plugins support. Still, there are some elements that can't be modified but I think it's a step forward
https://github.com/brainhubeu/react-carousel/pull/586
