### ISSUE TITLE
small offset doesn't give any effect

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#341]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/341)

It is:
1) provide a small offset like `800`
2) nothing changes
3) provide a larger offset like `900`
4) the image is slightly moved

It should be:
2) the image should be moved by 800px
4) the image should be moved by 900px

video: https://recordit.co/gRhUQ6spo1

example code to paste in docs:
```
<Carousel
  arrows
  offset={800}
>
  <img src={imageOne} />
  <img src={imageTwo} />
  <img src={imageThree} />
</Carousel>
```

@brainhubeu/react-carousel version: 1.12.19
it occurs in docs

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by Alucard17** [comment]
Hey @piotr-s-brainhub  how to get IssueHunt bounty for this issue

**Comment by piotr-s-brainhub** [comment]
@Alucard17 

we need to:
- check whether your solution resolves the problem
- check whether your solution doesn't break anything
- do a code review

**Comment by Alucard17** [comment]
Okay just let me know when code is reviewed

**Comment by piotr-s-brainhub** [comment]
@Alucard17 

I wrote in https://github.com/brainhubeu/react-carousel/pull/458 that it doesn't work for me.

**Comment by piotr-s-brainhub** [comment]
@Alucard17 

Are you going to fix this?

**Comment by RobertHebel** [comment]
@piotr-s-brainhub it's fixed in v1 and still needs to be fixed in v2
