### ISSUE TITLE
Documentation lacking for the breakpoints option

### ISSUE THREAD

**Issue by dagoss** [brainhubeu/react-carousel#355]
**Describe the bug**
In the documentation, the [responsive example](https://brainhubeu.github.io/react-carousel/docs/examples/responsive) isn't actually an example of a responsive carousel.

**Additional context**
I think at minimum the doc should show an example using the `breakpoints` option.

**Comment by piotr-s-brainhub** [comment]
Thanks @dagoss for suggestion.
I agree with you.
Do you think the following option will be OK?
```
breakpoints={{
  1200: {
    slidesPerPage: 2,
  },
  600: {
    slidesPerPage: 1,
  },
}}
```

**Comment by dagoss** [comment]
@piotr-s-brainhub 

Sure, that sounds fine. I also just put in a PR with an example that also shows how these aren't cumulative (for example, disabling arrows at 1200 will not also disable it at 600. Now that I think about it, is that the intended behavior?)

**Comment by piotr-s-brainhub** [comment]
@dagoss 

Regarding cumulative behavior, we can create another issue so we can consider introducing it in a new major release.
I'm not 100% sure about that as it has some advantages and disadvantages.

**Comment by piotr-s-brainhub** [comment]
or maybe there should be another prop which would work in a cumulative way so the carousel user could choose the preferred behavior

**Comment by piotr-s-brainhub** [comment]
I close this issue as it's now resolved in https://brainhubeu.github.io/react-carousel/docs/examples/responsive
