### ISSUE TITLE
dragging eventListeners are still added to carousel when dragging is disabled

### ISSUE THREAD

**Issue by chawomack** [brainhubeu/react-carousel#364]
**Describe the bug**
The carousel adds eventListeners for dragging even when dragging is disabled on the carousel. This prevents functionality like being able to select text on the carouselItem and all the children within a carouselItem.

**To Reproduce**
1. Create a carousel of text elements with `draggable={false}`
2. Try to highlight/select the text in each carousel item
3. You cannot select the text because the eventListeners are preventing default behavior

**Expected behavior**
These event listeners should only be added to the carousel items when dragging is enabled on the carousel.

**Additional context**
I've forked the repository and fixed the issue here:
https://github.com/chawomack/react-carousel/commit/f8456fc96ae8e0e140799d9f3d1a182f3d22c8a6#diff-47f9a611545f9ac1e92bcfa0131e590b

**Comment by FinnGu** [comment]
Just noticed this bug as well.
@chawomack Could you submit this as a pull request? Or if you don't have time at the moment, I could do that as well.

**Comment by chawomack** [comment]
I've opened a pull request https://github.com/brainhubeu/react-carousel/pull/366

**Comment by piotr-s-brainhub** [comment]
reproduction code:
```
<Carousel
  arrows
  draggable={false}
  slidesPerPage={2}
>
<div>foo</div>
<div>bar</div>
<div>baz</div>
</Carousel>
```
reproduction video: https://recordit.co/qgIeK9q9sD
video showing the fixed issue: https://recordit.co/d9CCs7NHg8
