### ISSUE TITLE
rewind

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#380]
`rewind` option (Boolean, default `false`) passed to the Carousel component.
If both `rewind` and `infinite` options are set to `true`, after the last slide, carousel moves all the slides to the opposite direction, starting again with the starting slide.
If `infinite` is `true` but `rewind` is `false`, carousel appends all the slides after the next slide, moving continuously all the time in the same direction.

**Comment by RobertHebel** [comment]
We don't have plans to add new features in carousel v1. In carousel v2 you can implement requested behavior by creating your own custom plugin https://brainhubeu.github.io/react-carousel/docs/plugins/creatingCustomPlugins
