### ISSUE TITLE
touchRatio

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#382]
`touchRatio` option (Number, default 1) passed to the Carousel component, specifying the ratio of items movement to the cursor movement so e.g. if it's 5, for 10px dragging, the carousel is moved by 50px but if it's 0.2, for 250 px dragging, the carousel is moved by 50 px.

**Comment by RobertHebel** [comment]
sorry @piotr-s-brainhub we decided we won't implement this feature
