### ISSUE TITLE
lazy loading of images

### ISSUE THREAD

**Issue by PsychoXIVI** [brainhubeu/react-carousel#389]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/389)

Original title: Images in slides are re-downloaded on every spin

**Describe the bug**
Images in slides are re-downloaded on every spin while using infinite sliding.

**To Reproduce**
1. Open [example with infinite sliding](https://brainhubeu.github.io/react-carousel/docs/examples/infinite).
2. Open Chrome DevTools
3. Move to Network tab
4. Click arrows to slide
And you can see more and more images re-downloaded...

**Expected behavior**
There should be no background loading of those! Those should load ONCE.

**Screenshots**
![image](https://user-images.githubusercontent.com/23557839/77825962-da0c3200-710c-11ea-9a78-ac9aa673cbae.png)

**Environment**
```
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 6.11 GB / 15.85 GB
  Binaries:
    Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
    Google Chrome: 80.0.3987.149
```
Desktop & mobile
Every browser...

**Additional context**
Good configured cache might help a bit, but still it generates network usage... :/

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars0.githubusercontent.com/u/20856232?v=4' alt='piotr-s-brainhub' width=24 height=24> piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($60.00)

### Submitted pull Requests
- [#531 389 Lazy load slides feature](https://issuehunt.io/r/brainhubeu/react-carousel/pull/531)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by piotr-s-brainhub** [comment]
@PsychoXIVI 

thanks for reporting but I'm not sure whether it's a valid bug.
I see sometimes there's some data downloaded from the server but I can change slides an unlimited number of times and no new data is downloaded.

Video: https://recordit.co/cnXA0mPOe2

Maybe you could write more details or maybe it happens only on Windows.

**Comment by piotr-s-brainhub** [comment]
For me, it works in a similar way on Windows, IE11.
Video: https://recordit.co/1tefzSkZn2

**Comment by PsychoXIVI** [comment]
I just checked it again - those are downloading for sure! I will try to make video too.

**Comment by PsychoXIVI** [comment]
Here is the video: https://streamable.com/ebkdh

Note:
* it seems like sliding right always make it to download.
* sliding left slowly is not triggering re-downloads, but fast sliding left yes.

**Comment by richardmint** [comment]
This definitely occurs to me as well whenever using Infinite scrolling. 

When advancing through the slides, a new image download is triggered and a new "list item" tag (<li>) is being inserted with a newly downloaded image. Is this intentional?

**Comment by piotr-s-brainhub** [comment]
@richardmint 

which OS and browser do you use?

**Comment by richardmint** [comment]
> @richardmint
> 
> which OS and browser do you use?

macOS Catalina (10.15.13) and Chrome (81.0.4044.122).

Happens on this demo page as well: https://brainhubeu.github.io/react-carousel/docs/examples/infinite

Open 
<img width="1017" alt="Screen Shot 2020-04-27 at 4 57 01 PM" src="https://user-images.githubusercontent.com/13142691/80432150-37300a80-88a8-11ea-8cf8-ada9fd5bb0eb.png">
<img width="707" alt="Screen Shot 2020-04-27 at 4 57 18 PM" src="https://user-images.githubusercontent.com/13142691/80432155-3a2afb00-88a8-11ea-9439-e553792170cc.png">

**Comment by piotr-s-brainhub** [comment]
@PsychoXIVI @richardmint 

I converted this issue to a feature request because IMO the current situation is acceptable.

If you want to open a PR, implementing lazy loading of images (when `lazyLoadingImages: true`), you're more than welcome.

**Comment by piotr-s-brainhub** [comment]
@richardmint 

I also invite you to like this issue (👍) so more 👍it has, it's more likely to be finished in the nearest time.
