### ISSUE TITLE
Additional classname support for Dots component

### ISSUE THREAD

**Issue by mikeechen** [brainhubeu/react-carousel#396]
**Is your feature request related to a problem? Please describe.**
It will be nice to customize the dots component a bit more than what is provided. 

**Describe the solution you'd like**
Allow passing classnames to the Dots component will be nice

**Describe alternatives you've considered**
Should be a simple props pass, and hopefully this will solve our problem of customizing the Dots component. 

**Additional context**
I'm creating a carousel component extending this one that can support multiple styles of carousels like scrolling bars with different margins and paddings, and this might be small but could enable us to customize our carousels further. 

I can create a small PR to get this started.

**Comment by piotr-s-brainhub** [comment]
@mikeechen 

Thanks for this proposal and your PR but could you explain what you couldn't use just `BrainhubCarousel__dots` class?

**Comment by mikeechen** [comment]
I did, but to help further customize it for our uses, I made it so that the clients will have to provide those classes, and just makes a cleaner experience for them to provide their own modular css instead of having to keep override your already made class with the global selector. Does that make sense?
```css
:global(.BrainhubCarousel__dots .BrainhubCarousel__thumbnail) {
  padding: 0;
  opacity: 1;
}
```

Trying to minimize this in our codebase as much as possible.

**Comment by mikeechen** [comment]
Also want to provide the option for them to turn the default css on or off, especially with your awesome thumbnail uses and the simple opacity change
```js
<Dots
      className={cs({ [styles.defaultDotsCss]: defaultCSS }, classes.thumbnail)}
      {...carouselProps}
      number={children.length}
      thumbnails={thumbnails}
    />
```

**Comment by piotr-s-brainhub** [comment]
OK if you have such needs

**Comment by ScriptedAlchemy** [comment]
@piotr-s-brainhub How would you feel about us possibly contributing to your repo from time to time. Id like to avoid an internal fork, your project is one of the cleanest carousels with no bloat like most others. 

Plus, OSS authors never have enough help. So this could be beneficial for all involved. Forking or writing carousels is always a maintenance nightmare. I'd rather contribute to a clean and solid solution, giving back to OSS community.

Let me know your thoughts

**Comment by piotr-s-brainhub** [comment]
@ScriptedAlchemy 

Absolutely, you're more than welcome to contribute to this repo.
