### ISSUE TITLE
Carousel has no width if parent uses Flexbox

### ISSUE THREAD

**Issue by alexmarles** [brainhubeu/react-carousel#406]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2456%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/406)

**Describe the bug**
I am using the carousel inside a section element which uses Flexbox, but the `BrainhubCarousel__track` and the `BrainhubCarouselItem` elements are all getting `width: 0px; max-width: 0px; min-width: 0px;`

**To Reproduce**
I created this [CodeSandbox](https://codesandbox.io/s/reverent-clarke-pljuc) which reproduces the issue.

**Expected behavior**
Slides and track elements should get the appropriate width.

**Screenshots**

**Environment**
```
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 241.82 MB / 16.00 GB
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.0.5
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $56.00)

- [<img src='https://avatars0.githubusercontent.com/u/20856232?v=4' alt='piotr-s-brainhub' width=24 height=24> piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($56.00)

### Submitted pull Requests
- [#466 Adds width to the carousel container, adds example in docs](https://issuehunt.io/r/brainhubeu/react-carousel/pull/466)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by piotr-s-brainhub** [comment]
reproduction code applicable in the docs/demo:
```
<div style={{display:'flex'}}>
<Carousel
  arrows
>
  <img src={imageOne} />
  <img src={imageTwo} />
  <img src={imageThree} />
</Carousel>
</div>
```

**Comment by Kvintus** [comment]
Hello, I had that same problem when I wanted to centr the carousel inside a flexbox div. 
Solved it by setting the parent's display property to "grid".
Hope it helps :)

**Comment by piotr-s-brainhub** [comment]
@Kvintus

I got the following email notification but I cannot see your comment here.
```
Hello, I had that same problem when I wanted to centr the carousel inside a flexbox div.
Solved it by setting the parent's display property to "grid".
Hope it helps :)
```

Have you deleted this comment?

**Comment by max-arias** [comment]
PR to fix this issue: https://github.com/brainhubeu/react-carousel/pull/466

(I also update gatsby, it was failing to render docs-www)

**Comment by piotr-s-brainhub** [comment]
@max-arias 

Could you address the last comments in https://github.com/brainhubeu/react-carousel/pull/467 ?
