### ISSUE TITLE
Expected `event` listener to be a function, instead got `false`.

### ISSUE THREAD

**Issue by Lagicrus** [brainhubeu/react-carousel#407]
**Describe the bug**
When loading the component, I get 70 errors in rapid succession.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run dev build (so don't build)
2. Use this code
```js
<Carousel
          slidesPerPage={2} arrows infinite centered draggable={false}
          arrowLeft={<ArrowBackIosIcon className="mouseOver"/>}
          arrowRight={<ArrowForwardIosIcon className="mouseOver"/>} addArrowClickHandler>
          {this.state.latestPrefabData.map(item => (
            <PrefabCard data={item} key={item.id}/>
          ))}
        </Carousel>
```
3. Load page

**Expected behaviour**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/24227350/78583894-58648480-782f-11ea-9303-e31ff4a17887.png)

**Environment**
System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver) (WSL)
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 15.97 GB / 31.95 GB
  Binaries:
    Node: 12.16.1 - /usr/bin/node
    npm: 6.14.4 - 
  npmPackages:
    @brainhubeu/react-carousel: 1.13.22 => 1.13.22
- Desktop Windows 10
- Browser Chrome

**Additional context**

**Comment by Lagicrus** [comment]
Closed as upgrading to .24 seems to have fixed it after a hard reload

**Comment by weignerg** [comment]
I am having the same issue.
Upgrade to .24 of what?

**Comment by piotr-s-brainhub** [comment]
@weignerg 

I guess `react-carousel@1.13.24`
