### ISSUE TITLE
itemWidth not working within breakpoints

### ISSUE THREAD

**Issue by kris10cabrera** [brainhubeu/react-carousel#411]
**Describe the bug**
The `itemWidth` attribute is not working within breakpoints.
```
        itemWidth={660}
        breakpoints={{
          800: {
            itemWidth: 200
          }
```

**To Reproduce**
1. Within the `Carousel` component, set an `itemWidth`
2. Add a breakpoint and a different `itemWidth`

**Expected behavior**
The itemWidth at screenwidths less than 1000px should be at 10px

**Screenshots**
<img width="675" alt="Screen Shot 2020-04-07 at 3 14 55 PM" src="https://user-images.githubusercontent.com/40896596/78709990-97074700-78e2-11ea-9e98-fab5cc5c3948.png">

**Environment**
- desktop mac
- Chrome

**Comment by piotr-s-brainhub** [comment]
@kris10cabrera 

Thanks for reporting this issue.
I managed to reproduce it.
Maybe we'll fix it as it's maybe not difficult to fix.
However, a PR from your part would be more than welcome.

**Comment by kris10cabrera** [comment]
@piotr-s-brainhub thanks for your response. I noticed this is also a problem with the `draggable` attribute.

**Comment by kris10cabrera** [comment]
@piotr-s-brainhub do you have any suggestions for workarounds? I need my `itemWidth` to be 780 on screenwidths larger than 800px, but on small screens I'd like it to be smaller. I tried to override the styles in the css by using `!important`, but the swipe width stays at 780.

**Comment by piotr-s-brainhub** [comment]
@kris10cabrera 

For now, I don't have any idea for a workaround.
Maybe it's easier to fix this issue than do a workaround.

**Comment by piotr-s-brainhub** [comment]
reproduction code applicable in the live docs/demo:
```
<Carousel
  slidesPerPage={3}
  arrows
  itemWidth={600}
  breakpoints={{
    900: {
      slidesPerPage: 1,
      arrows: false,
      itemWidth: 200
    },
  }}
>
  <img src={imageOne} />
  <img src={imageTwo} />
  <img src={imageThree} />
</Carousel>
```
