### ISSUE TITLE
Dots <div type="button"> is not valid HTML

### ISSUE THREAD

**Issue by mikeechen** [brainhubeu/react-carousel#417]
**Describe the bug**
For dots, you're rendering them with <div type="button">, as I understand this is not really a valid HTML. In this case, we should just go with a <button> tag to also make them more accessible.

**To Reproduce**
1. Make a carousel with dots.
2. See that the dots are rendered with <div type="button">...

**Expected behavior**
Render valid HTML in order for screen readers to identify these buttons to improve accessibility for the carousels.

**Screenshots**
![image](https://user-images.githubusercontent.com/20528229/78947600-a8835700-7a7a-11ea-9d50-721180cd7fad.png)

**Environment**
 System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 312.00 MB / 16.00 GB
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 81.0.4044.92
    Firefox: 73.0.1
    Safari: 13.1

**Additional context**
I can make another PR to fix this issue if you like. I'm thinking we might be able to just switch to a button tag and override the default button css styles and hopefully we can keep them looking the same as before.

**Comment by piotr-s-brainhub** [comment]
@mikeechen 

thanks for reporting, a PR would be more than welcome

**Comment by humbak** [comment]
@mikeechen issue fixed. Thanks.
