### ISSUE TITLE
docs don't show import

### ISSUE THREAD

**Issue by capaj** [brainhubeu/react-carousel#420]
please add imports to the doc examples

**Comment by piotr-s-brainhub** [comment]
@capaj 

Could you be more specific?

We have already imports in our docs https://github.com/brainhubeu/react-carousel/blob/master/docs/gettingStarted.md

And the examples like that https://github.com/brainhubeu/react-carousel/blob/master/docs/examples/animation.md are aimed to not be too long.

**Comment by RobertHebel** [comment]
Fixed in v2 docs
