### ISSUE TITLE
Warnings on draggable=false

### ISSUE THREAD

**Issue by weignerg** [brainhubeu/react-carousel#425]
https://github.com/brainhubeu/react-carousel/blob/bf8f7e76e9e0cac73e69c685a0df1e2483dbdb5f/src/components/CarouselItem.js#L46

![image](https://user-images.githubusercontent.com/29870826/79154831-d972cd00-7d95-11ea-845f-760111b182fd.png)

False is being passed rather than the function when draggable is set to false.

Would this code work?

`{
this.props.isDraggingEnabled && ...(
onMouseDown={this.onMouseDown}
onTouchStart={this.onTouchStart}
)
}`

**Comment by weignerg** [comment]
Conditionally add the prop of a function rather than add a prop conditionally false or function.

**Comment by piotr-s-brainhub** [comment]
@weignerg 

Thanks for reporting this but I'm not able to reproduce this issue.
<img width="1350" alt="Screenshot 2020-04-13 at 22 42 10" src="https://user-images.githubusercontent.com/20856232/79159305-1eb7ee80-7dd8-11ea-9741-89d4196826df.png">

Could you provide an example code possible to paste into the demo/ docs and what's needed to perform In order to see these warnings?

Regarding improvements, the simplest will be if you open a PR.

**Comment by weignerg** [comment]
These are warning that show up in development build.
Production build does not show the warnings.

I am not yet familiar with how to go about making the change, testing it and submitting the pull request.

**Comment by weignerg** [comment]
To reproduce, start a development application and navigate to a page with a carousel that has the draggable prop set to false.

**Comment by piotr-s-brainhub** [comment]
@weignerg 

Neither locally I can reproduce that.
I set `draggable` to `false` and I click the image and I see no warnings.
<img width="1100" alt="Screenshot 2020-04-14 at 01 37 46" src="https://user-images.githubusercontent.com/20856232/79170819-c7724800-7df0-11ea-9e82-0deb82e2546e.png">
The only warnings are generated after the page reload.

**Comment by weignerg** [comment]
I am using it in a typescript file.

Is the version being used.
  "dependencies": {
    "@brainhubeu/react-carousel": "^1.13.19",
    "@types/brainhubeu__react-carousel": "^1.10.2",

**Comment by weignerg** [comment]
This looks like a duplicate of this issue.

https://github.com/brainhubeu/react-carousel/issues/407

**Comment by weignerg** [comment]
Issue not present in later version.

I upgraded to newest version of the react carousel.

npm i @brainhubeu/react-carousel
"@brainhubeu/react-carousel": "^1.13.32",

npm i @types/brainhubeu__react-carousel -D
"@types/brainhubeu__react-carousel": "^1.13.0",
