### ISSUE TITLE
'offset' prop doesn't work together with 'infinite' prop

### ISSUE THREAD

**Issue by wsl1** [brainhubeu/react-carousel#43]

**Comment by adam-golab** [comment]
I'm closing this issue in favor of #65

**Comment by piotr-s-brainhub** [comment]
@wsl1 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
