### ISSUE TITLE
Whats needed for basic SSR?

### ISSUE THREAD

**Issue by ScriptedAlchemy** [brainhubeu/react-carousel#443]
**Is your feature request related to a problem? Please describe.**
I want to render out the images server-side, perhaps with a css overflow to prevent a long list of images floating down the page while CSR hydrates

**Describe the solution you'd like**
The ability to no execute the specific method, or render the function that causes SSR to fail

**Describe alternatives you've considered**
Forking, but id rather help maintain than help fragment a good project 

**Additional context**
I wrote most the SSR mechanics that next.js `dynamic` is based off of and wrote the first code-split SSR utility back in the day. I know my way around SSR, just want to know what the issue is and will you accept the change if i burn time doing it.

**Comment by piotr-s-brainhub** [comment]
@ScriptedAlchemy 

Thanks for your question.
Please try [this](https://github.com/brainhubeu/react-carousel#ssr) but it's only a workaround, not a real SSR.

There's already a feature request [here](https://github.com/brainhubeu/react-carousel/issues/376). I just added 1 USD on IssueHunt for that issue but if you'd like to get more, you can request a bounty, writing your proposed amount so I can discuss your amount with the team.
<img width="889" alt="Screenshot 2020-04-16 at 01 32 59" src="https://user-images.githubusercontent.com/20856232/79399078-a2adda00-7f82-11ea-82af-53829115763e.png">

**Comment by ScriptedAlchemy** [comment]
Lol I’ll add the USD just to support you. But I’m more than willing to work long side your team. I’ve suggested we use this carousel at the company. If we do - you’d likely get more contributions from us as there’s the occasional feature the carousel might support. All Contributions will start as got issues to confirm you’re happy with an addition and to lose explain the user / business value proposition. 

If we contribute regularly, it would be useful if a trusted source, like myself, with long term OSS experience and high profile project involvement were able to become a maintainer (unblocking critical bug fixes without the need to npm publish a strong copy) - this is all a conversation for a future time though,first step is we need to bring value to the project haha. 


I’ll take a look at your suggestions, but let me know if you’re open to me creating a pull request adding some simply SSR capabilities

**Comment by piotr-s-brainhub** [comment]
@ScriptedAlchemy 

It will be great if you open a PR with SSR and you become an active contributor.
Regarding maintainers, IMO only the Brainhub employees should have a right to merge to `master` which publishes a new NPM version. It could be an option only if none of us had enough time for that.

**Comment by ScriptedAlchemy** [comment]
Understandably so, and I do see where you are coming from too! (I've got 20 million active users dependent on my OSS stuff) 

I didn't realize this was maintained by a company, that's good to know! Looking at this from a risk mitigation aspect, free OSS maintainers often get bogged down which becomes a risk to companies if they cant get responses or merges from authors. 

I feel way more comfortable knowing this is backed by a company. No need for maintainership unless you see a reason, happy to leave it in your hands and contribute :) 

Will take a look at SSR once our UX department finalizes all the varients of a carousel in the DSM. I'm planning to use yours as the standardized carousel sitewide. If I've got some time, ill make an early start on SSR and see where we get it too.

Great work on this carousel, one of the cleanest I've come across. Big kudos

**Comment by piotr-s-brainhub** [comment]
@ScriptedAlchemy 

Are you going to open a PR?
Or maybe we could close this issue as it's a question and it's answered.

**Comment by ScriptedAlchemy** [comment]
I’ve been a little backed up with webpack work. We can close it out and reopen it when I submit a PR. I will have to do it. Just timing

**Comment by piotr-s-brainhub** [comment]
@ScriptedAlchemy 

So I close this issue and the SSR feature request is reported there https://github.com/brainhubeu/react-carousel/issues/376
