### ISSUE TITLE
Images only?

### ISSUE THREAD

**Issue by jutunen** [brainhubeu/react-carousel#450]
Sorry about my stupid question, but is this carousel only for images? I just can't find this information anywhere...

**Comment by piotr-s-brainhub** [comment]
@jutunen 

Not only. It can work with any React component.
e.g.:
```
<Carousel
  arrows
>
<div>foo-1</div>
<div>foo-2</div>
<div>foo-3</div>
<div>foo-4</div>
<div>foo-5</div>
</Carousel>
```

**Comment by jutunen** [comment]
OK, thanks for the info. That was fast! I'm closing this issue. Thanks again!
