### ISSUE TITLE
one command to run locally with live update

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#454]
As in README:
if you want to connect demo with the carousel source code, replace __RC_ENV__ into development in https://github.com/brainhubeu/react-carousel/blob/master/docs-www/src/globalReferences.js#L2 and remove the `.babelrc` file in the root directory; otherwise, it will use the carousel code installed in `docs-www/node_modules`

It would be nice to have one command to do that and avoid modifying `.babelrc` and `docs-www/src/globalReferences.js` which are needed to check out before doing a commit.

**Comment by RobertHebel** [comment]
Fixed in carousel v2
