### ISSUE TITLE
breaks click and touch events

### ISSUE THREAD

**Issue by jquense** [brainhubeu/react-carousel#47]
Hey there, It seems like the carousel globally prevents click/touch events for events outside (or inside the component). It'd also be nice if dragging had to be initiated inside the carousel so that scrolling didn't also move the slides

**Comment by kruulik** [comment]
Hi, any fix to this issue? I just noticed this behavior on a site I am working on. Touch events are completely ignored, and dragging on the x-axis anywhere on the page moves the carousel too.

**Comment by orangecms** [comment]
Hey there, I've rebased and created a fixup for @kruulik's patch:
https://github.com/orangecms/react-carousel/commit/f3679988ba54754ab82c50495aef0824de4b72dd

I'll see if I can work on a test case. :)

**Comment by micabe** [comment]
Any progress on this ?

**Comment by piotr-s-brainhub** [comment]
@jquense @kruulik 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
