### ISSUE TITLE
'minDraggableOffset' does not exist in type 'CarouselProps'

### ISSUE THREAD

**Issue by mrsamse** [brainhubeu/react-carousel#478]
The docs (https://brainhubeu.github.io/react-carousel/docs/api/carousel) says, that I Could use "minDraggableOffset". But if I use it in my typescript project, I'll get this error: 
'minDraggableOffset' does not exist in type 'CarouselProps'

**Comment by piotr-s-brainhub** [comment]
@mrsamse 

Does `minDraggableOffset` work for you without TypeScript?

**Comment by sinchang** [comment]
I have created a PR to fix this issue on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44949. 

install latest types package 

```
npm i @types/brainhubeu__react-carousel -D
```
could you verify it is resolved?
