### ISSUE TITLE
multiple rows

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#484]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/484)

`numberOfRows` param (type: Number, default: 1) passed to the Carousel component telling about the number of rows.

When a slide reaches the end of a given row, it should be moved to the start of the next row.

When the carousel is vertical, instead of rows, there should be columns.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by piotr-s-brainhub** [comment]
@coderanshu602 @k3d61

I see both of you requested a bounty of 40 USD for fixing this issue.
Does it mean you want to fix it for 40 USD or for only 66 USD (26 + 40)?

**Comment by piotr-s-brainhub** [comment]
@coderanshu602 @k3d61 ?

**Comment by therajdeepbiswas** [comment]
I am willing to contribute. Can you provide the steps to reproduce the issue?

**Comment by piotr-s-brainhub** [comment]
@therajdeepbiswas 

It's a feature request, not a bug.

**Comment by therajdeepbiswas** [comment]
@piotr-s-brainhub I'm new to this repository, please tell me which function should I modify or which file should I be adding a function to.

**Comment by piotr-s-brainhub** [comment]
@therajdeepbiswas 

Probably, you should modify [this file](https://github.com/brainhubeu/react-carousel/blob/master/src/components/Carousel.js) but it would be good to also update tests.

**Comment by therajdeepbiswas** [comment]
Excuse me if I'm making a beginner mistake but the code in `Carousel.js` seems to me to be very tightly coupled together to stick to the design it has been made before; I don't see a possibility of implementing the `numberOfRows` feature without having to refactor a lot of the preexisting code. If you could show me a visual sample of what is being asked, maybe then I could understand the problem a little better.

**Comment by piotr-s-brainhub** [comment]
@therajdeepbiswas 

I agree that a refactor is needed and we're planning to do that in the nearest few weeks so you can wait until we finish refactoring. The issue about this refactor: https://github.com/brainhubeu/react-carousel/issues/339.

**Comment by RobertHebel** [comment]
@piotr-s-brainhub we decided we won't introduce this feature in carousel v1.
