### ISSUE TITLE
onChange only fires when value prop is explicitly set on carousel

### ISSUE THREAD

**Issue by albanyacademy** [brainhubeu/react-carousel#487]
**Describe the bug**
onChange only fires when an explicit value is passed to the Carousel component.

**To Reproduce**
https://codesandbox.io/embed/react-playground-cv3eg?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
onChange should fire whenever the slide's changing, regardless of explicit value being passed.

**Comment by albanyacademy** [comment]
This also presents problems when using infinite, as the active slide value is calculated by the carousel and never exposed by it.

**Comment by piotr-s-brainhub** [comment]
@albanyacademy 

Thanks for reporting this issue but I cannot understand it.

What do you mean by the explicit value?

Why do you have `onChange={() => handleChange}` in the sandbox but not `onChange={handleChange}`?

**Comment by piotr-s-brainhub** [comment]
@albanyacademy 

could you reply?

**Comment by Romcol** [comment]
Hi,

That's true. It only works when the carousel is fully controlled.
See https://codesandbox.io/s/react-playground-zuodu :wink:

**Comment by albanyacademy** [comment]
Sorry yeah, romcol better illustrates it. When you slide the top slide, onChange fires, but the bottom slide doesn't fire onChange. It looks like onChange is only supposed to be used with a react state, but it would be nice if it was a bit more consistent and applicable within a react component. What caused me to find this was just needing the carousel to update a meta box once the slide finished changing; I'd grab the slide's index and match it to some json data, then update the metabox component. But because onChange didn't work unless I took direct control over the carousel's behaviour, I just used createRef to listen for transitionEnd.

it would be nice if onChange was a more broad callback that you could hook into without having to take over the behaviour directly.

**Comment by piotr-s-brainhub** [comment]
@Romcol @albanyacademy 

Thanks so I see that `onChange` isn't called if the `value` isn't explicitly set.

**Comment by piotr-s-brainhub** [comment]
code applicable in clickable docs:
```
<Carousel
  arrows
  onChange={value=>console.log('onChange', {value})}
>
  <img src={imageOne} />
  <img src={imageTwo} />
  <img src={imageThree} />
</Carousel>
```
video: https://recordit.co/uIw2qmCkao
