### ISSUE TITLE
How to setup development

### ISSUE THREAD

**Issue by mishranant** [brainhubeu/react-carousel#491]
Hello there, I am very new to open-source as well as React development. So, apologies in advance if this turns out to be a silly question.

Steps performed:
1. `git clone https://github.com/brainhubeu/react-carousel && cd react-carousel`
2. `npm install` to install all dependencies
3. `npm run build`

this produces static js and css files in the /lib directory ready to use in production. But how to 'run' those files in the sense of finding out how the output looks like.
If I change the source code in /src and perform `npm run build` again, that must be reflected in the /lib folder. But, how do I visualize what has changed in the Carousel component?

**Comment by piotr-s-brainhub** [comment]
@mishranant 

Thanks for asking.

I opened https://github.com/brainhubeu/react-carousel/pull/493/files

I recommend connecting the carousel with the source code (not in `node_modules`) in order to reflect changes after each update.

**Comment by RobertHebel** [comment]
Solved. Closing
