### ISSUE TITLE
Remove deprecated method

### ISSUE THREAD

**Issue by Lukasz-pluszczewski** [brainhubeu/react-carousel#50]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/50)

Library uses deprecated method (componentWillReceiveProps) to turn animation on and off (depending on the actual change of carousel value prop). We should implement it using e.g. getDerivedStateFromProps or some other method.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/20856232?v=4' alt='piotr-s-brainhub' width=24 height=24> piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($5.00)

### Submitted pull Requests
- [#197 Remove componentWillReceiveProps. Fixes #50.](https://issuehunt.io/r/brainhubeu/react-carousel/pull/197)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by damian-brainhub** [comment]
As a part of this issue, we please consider also abstracting away Carousel from React. This should allow us to:

* simplify updating to latest React versions
* simplify testing
* in future we would be able to port it to Vue and other frameworks

**Comment by danedavid** [comment]
> As a part of this issue please consider also abstracting away carousel from React.

What do you mean by this?

**Comment by piotr-s-brainhub** [comment]
@danedavid 
I don't think it's needed because it would mean we couldn't use JSX. Morever, carousel would be still dependent on some interface. IMO we should do the best job about a carousel in React and there could be another library for Vue.

@damian-szulc 
What do you think?

**Comment by piotr-s-brainhub** [comment]
@danedavid 

Are you willing to fix this issue?

**Comment by danedavid** [comment]
@piotr-s-brainhub  Yes, I can take a look at it by this weekend.

**Comment by piotr-s-brainhub** [comment]
I checked the `componentWillReceiveProps` method is removed and everything is still working (both desktop and mobile).

**Comment by piotr-s-brainhub** [comment]
@danedavid 

I have a question: are you able to withdraw any funds from the issuehunt?
I ask because after writing to info@issuehunt.io, asking them for an invoice and waiting more than one week, I still have no reply.
And in order to withdraw any funds, it's required to send an email to info@issuehunt.io as well.

**Comment by danedavid** [comment]
@piotr-s-brainhub Never tried yet
