### ISSUE TITLE
Blank carousel while loading

### ISSUE THREAD

**Issue by Romcol** [brainhubeu/react-carousel#514]
Hi,

When the carousel is loading, we can see that the space it should be filling is going blank.
In this respect, when making our own SSR implementation of the slider we can see that there is a moment when the carousel is blank.

This following video should be more explicit:

[![Carousel](https://res.cloudinary.com/marcomontalbano/image/upload/v1591367727/video_to_markdown/images/vimeo--426259397-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://vimeo.com/426259397 "Carousel")

Do you have any ideas on how to fix this? I didn't experience this issue while using other lib (such as `react-slick`) but we decided to switch to `react-carousel` ;)

Thank you :rocket: !

**Comment by piotr-s-brainhub** [comment]
@Romcol 

Thanks for reporting this. I guess it will be fixed when https://github.com/brainhubeu/react-carousel/issues/376 is implemented.

**Comment by Romcol** [comment]
@piotr-s-brainhub 

Hi, Is there a way to know when the carousel is "ready" ? If so we can wait for the ready state to show the slider.

**Comment by piotr-s-brainhub** [comment]
@Romcol 

AFAIK there's no such way and as you can see, after the carousel being loaded, when you switch slides fast, it can become blank.
