### ISSUE TITLE
Usage example with TypeScript

### ISSUE THREAD

**Issue by lopno** [brainhubeu/react-carousel#52]
It would be nice with a simple example of how to import and use react-carousel with TypeScript in the documentation.

**Comment by adam-golab** [comment]
I'm closing this issue, as it's fixed by #66

**Comment by piotr-s-brainhub** [comment]
@lopno 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
