### ISSUE TITLE
Slider is broken on dir="rtl" pages.

### ISSUE THREAD

**Issue by humbak** [brainhubeu/react-carousel#53]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/53)

To reproduce that case just add dir="rtl" to <HTML> tag.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/20856232?v=4' alt='piotr-s-brainhub' width=24 height=24> piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by ali-hellani** [comment]
any updates on this ?!

**Comment by konyan** [comment]
I want to solve this issues.

**Comment by piotr-s-brainhub** [comment]
@konyan 

So a PR is welcome. We don't assign people to issues so many people can fix the same issue in the same time. However, your comment can cause other people will choose other issues instead this one.

**Comment by konyan** [comment]
Thanks @piotr-s-brainhub ,
This is my first time contribution. I may be miss understand  about issues.
I don't also find CONTRIBUTE guide. My Solution is attached below.

### Add New PropTypes Bool name => rtl  
![Screen Shot 2019-10-03 at 2 36 31 AM](https://user-images.githubusercontent.com/6771972/66077778-a5b52000-e586-11e9-8af4-7cc64db3ae2a.png)

### Some Code changes in renderCarouselItems function

![Screen Shot 2019-10-03 at 2 33 16 AM](https://user-images.githubusercontent.com/6771972/66077702-81594380-e586-11e9-9748-adf5e9ffbc95.png)

**Comment by piotr-s-brainhub** [comment]
@konyan 

You can:
- fork this repo
- do needed changes
- commit
- push to your fork
- open a pull request from your fork/branch to this repo (`master` branch)

You can learn it e.g. from https://youtu.be/_NrSWLQsDL4

**Comment by piotr-s-brainhub** [comment]
@konyan 
are you going to open a PR?

**Comment by piotr-s-brainhub** [comment]
@konyan 

do you still want to fix this?

**Comment by sinchang** [comment]
Hi, anyone working on this issue?

**Comment by piotr-s-brainhub** [comment]
@sinchang 

I don't think anybody is currently working on this issue so you're more than welcome to open a PR.
Even if somebody does, the winner is the person who resolves successfully the issue as the first.

**Comment by katiawheeler** [comment]
@piotr-s-brainhub any update on a release date for this?

**Comment by piotr-s-brainhub** [comment]
@katiawheeler 

It depends on when @sinchang resolves code review comments and conflicts but if it's important to you, we can do it on ourselves in the nearest few days.

**Comment by katiawheeler** [comment]
@piotr-s-brainhub We are looking into implementing RTL site-wide and will need it in the upcoming month, so not urgent but would definitely like to see it!

**Comment by katiawheeler** [comment]
@piotr-s-brainhub any update on this? We're hoping to use it soon.

**Comment by piotr-s-brainhub** [comment]
@katiawheeler 

There are still some problems with https://github.com/brainhubeu/react-carousel/pull/221 and now also some conflicts.

You can check https://beghp.github.io/gh-pages-rc-3/docs/examples/rtl and other examples under that domain with `rtl` attribute.

If that `rtl` implementation śatisfies your need, I can publish it as an alpha version.

You can also contribute, opening a PR into `pr-183-sinchang-bot-rtl` branch.

If you misses something and neither your nor @sinchang has enough time to fix that, we can try to update the RTL PR.

**Comment by sinchang** [comment]
@piotr-s-brainhub sorry, I have no idea how to fix that. glad that if someone can help

**Comment by piotr-s-brainhub** [comment]
@sinchang 

OK so I can take a look.
