### ISSUE TITLE
onClick event can not fired on mobile

### ISSUE THREAD

**Issue by asaism** [brainhubeu/react-carousel#54]
Hi there, I implement a close button in the carousel. I set the onClick event for that close button. The onClick event does not fired when I try to make it work on mobile.
Please tell me the solution or workaround.
Best regards,
Suguru

**Comment by damian-brainhub** [comment]
related to https://github.com/brainhubeu/react-carousel/issues/47 . Moving there

**Comment by piotr-s-brainhub** [comment]
@asaism 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
