### ISSUE TITLE
docs: /docs/ & /docs/examples/ give "not found" error

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#543]
<img width="864" alt="Screenshot 2020-06-17 at 16 04 41" src="https://user-images.githubusercontent.com/20856232/84908308-9b0ace80-b0b4-11ea-99b1-ac69e396b290.png">
<img width="856" alt="Screenshot 2020-06-17 at 16 04 48" src="https://user-images.githubusercontent.com/20856232/84908321-9d6d2880-b0b4-11ea-9f24-cec06b820456.png">

https://brainhubeu.github.io/react-carousel/docs/ should redirect to https://brainhubeu.github.io/react-carousel/docs/gettingStarted

https://brainhubeu.github.io/react-carousel/docs/examples/ should redirect to https://brainhubeu.github.io/react-carousel/docs/examples/simpleUsage

**Comment by RobertHebel** [comment]
I believe this is https://github.com/brainhubeu/gatsby-docs-kit issue, not react-carousel. Please reopen this issue in the correct repo
