### ISSUE TITLE
@zkwentz

### ISSUE THREAD

**Issue by codeWebZhang** [brainhubeu/react-carousel#553]
@zkwentz 

thank you very much

_Originally posted by @piotr-s-brainhub in https://github.com/brainhubeu/react-carousel/issues/549#issuecomment-647193228_

I have the same issue; localhost is running, release is wrong;

**Comment by piotr-s-brainhub** [comment]
@codeWebZhang 

I close this issue, please write a comment in https://github.com/brainhubeu/react-carousel/issues/549 instead.
