### ISSUE TITLE
Changing carousel property during runtime

### ISSUE THREAD

**Issue by briankosw** [brainhubeu/react-carousel#578]
Is there a way to change carousel properties, such as the slidesPerPage, during runtime? I tried to change the state by using `this.setState()` but the change doesn't reflect on the carousel.

**Comment by piotr-s-brainhub** [comment]
@briankosw 

Why did you close this issue?

**Comment by briankosw** [comment]
I asked the question prematurely and realized it was a stupid question. My bad!

**Comment by piotr-s-brainhub** [comment]
No problem.

react-carousel supports a controlled component.
