### ISSUE TITLE
Passive Event Listeners Google Lighthouse

### ISSUE THREAD

**Issue by Fubinator** [brainhubeu/react-carousel#581]
**Describe the bug**
If you install the slider and run Google's Lighthouse, the error "Does not use passive listeners to improve scrolling performance" appears under "Best Practices" (see screenshot). This is probably caused by multiple event listeners.

**Expected behavior**
The message should not appear in a lighthouse report.

**Screenshots**
![image](https://user-images.githubusercontent.com/16110028/86356471-988ba580-bc6c-11ea-9dde-6dbb9cf6b86c.png)

**Environment**

System:
    OS: Linux 5.7 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 1.77 GB / 15.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.4.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Firefox: 77.0.1
  npmPackages:
    @brainhubeu/react-carousel: ^1.16.3 => 1.16.3

**Comment by piotr-s-brainhub** [comment]
@Fubinator 

Thanks for reporting this.

Do you encounter this error only in the Google Lighthouse or maybe also in some other places?

Can you see this error for the docs https://brainhubeu.github.io/react-carousel/docs/examples/simpleUsage ?

**Comment by Fubinator** [comment]
@piotr-s-brainhub yes, i'm encountering the error for the docs:

![image](https://user-images.githubusercontent.com/16110028/86447255-5b2f2280-bd15-11ea-871c-891e0e04b5eb.png)

In other places I have not yet seen the error. This is only about the given best practices of Google Lighthouse.

I've digged a little bit in the code and I think the error occurs in the following lines:

https://github.com/brainhubeu/react-carousel/blob/c1e255220609003cf468c558108cf81b6b57bd9e/src/components/Carousel.js#L97-L103

I am not exactly sure why there is one listener set to `passive: false`, but it may help if the other ones are set to `passive: true`

**Comment by piotr-s-brainhub** [comment]
Thanks @Fubinator , I also see this error.
<img width="849" alt="Screenshot 2020-07-06 at 20 38 24" src="https://user-images.githubusercontent.com/20856232/86627510-be94ab00-bfc8-11ea-916f-8816965c64ab.png">

**Comment by kelyvin** [comment]
+1

 I am seeing this warning in the chrome developer console when react-carousel loads. 

![Screen Shot 2020-07-13 at 3 45 56 PM](https://user-images.githubusercontent.com/1530102/87360954-06af5280-c520-11ea-9970-db9558f21949.png)

**Comment by piotr-s-brainhub** [comment]
@kelyvin so I invite you to like (👍) this issue we could compare issues by the number of 👍

**Comment by kelyvin** [comment]
You got it!

**Comment by piotr-s-brainhub** [comment]
thanks @kelyvin

**Comment by RobertHebel** [comment]
The issue has been fixed in v1.19.23. If the problem will occur for you please let me know and I will reopen this thread
