### ISSUE TITLE
Without empty space around the edges

### ISSUE THREAD

**Issue by Dima-Dim** [brainhubeu/react-carousel#582]
Faced the following behavior:
There may be 2 slides in the gallery, with the value slidesPerPage = 2 and centered, when you select the slides, they move both left and right, there is an empty space, which may not be desirable, you just need to change the active slide without moving anything, because the page already has all the slides displayed.
The following is not desirable behavior with the same settings, but with more slides. If the first or last slides are selected, either left or right, an empty space remains.

Is it possible to add a setting that would make it possible not to create this free space?

**Comment by piotr-s-brainhub** [comment]
@Dima-Dim 

Do you think it's the same as https://github.com/brainhubeu/react-carousel/issues/501 ?

**Comment by Dima-Dim** [comment]
Yes, really! Thank! He put his finger up ;)

**Comment by piotr-s-brainhub** [comment]
Thanks so I close this issue.
