### ISSUE TITLE
Multiple slides not showing

### ISSUE THREAD

**Issue by kingRayhan** [brainhubeu/react-carousel#619]
I tried to show multiple item at a time by this example
https://brainhubeu.github.io/react-carousel/docs/examples/multipleSlides

I get one slide always.

Here is the sandbox where I tried to explore 
https://codesandbox.io/s/react-carousel-666fs?file=/src/App.js:252-1571

**Comment by RobertHebel** [comment]
The docs on the master branch were referring to the carousel v2 which will be released soon. Now they are referring v1 version again
