### ISSUE TITLE
Too big width for no reason

### ISSUE THREAD

**Issue by Arrow891** [brainhubeu/react-carousel#63]
I have a big issue, when the carousel renders, it breaks down, and when I check the element's width, I see a very large scale which is not logical
![toobig](https://user-images.githubusercontent.com/23627951/47120777-cb192300-d27c-11e8-8c6f-b44f00e694b8.png)
This is urgent for me to fix this, please inform me if there is any solution

**Comment by szulcd2** [comment]
hi! Could you share your code? Or could you prepare snippet to reproduce this issue? We don't hear this bug report often so we need to understand better what is going on.

**Comment by Arrow891** [comment]
@damian-brainhub Hi! I also searched a lot on the net and I could not find any reliable solution, but during my tests, I figured out that 2 of my parent elements are using "flex" so I set the `min-width: 0` for both of them and it did the trick and fixed the issue.

**Comment by piotr-s-brainhub** [comment]
@Arrow891 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by ruaanvds** [comment]
Just in case this helps someone - I worked around this issue by just wrapping the carousel in a div with `display:block; width:100%`.

**Comment by renchris** [comment]
i still have this issue. the min-width: 0 or div with display:block; width:100% particularly didnt work for me

**Comment by balean12** [comment]
In order to solve this I actually did a combination of a new div with display: grid and width: 100% wrapped around the carousel
