### ISSUE TITLE
Error when refresh - Cannot update a component while rendering a different component

### ISSUE THREAD

**Issue by tsanyqudsi** [brainhubeu/react-carousel#648]
**Describe the bug**
`Warning: Cannot update a component (`Ne`) while rendering a different component (`hn`). To locate the bad setState() call inside `hn`, follow the stack trace as described in https://fb.me/setstate-in-render
    in hn
    in RecoilRoot`

**To Reproduce**
1. Install using v.2.0.1
2. Import and Implement the component
3. Refresh the page used by the component
4. See error on the console

**Expected behavior**
There's no error

**Screenshots**
![Screenshot from 2020-10-03 17-40-57](https://user-images.githubusercontent.com/1050880/94989546-dd8ee300-059f-11eb-96a0-2473a82b1516.png)

**Environment**
System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz
    Memory: 366.87 MB / 7.67 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.13.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
  Browsers:
    Firefox: 81.0
  npmPackages:
    @brainhubeu/react-carousel: ^2.0.1 => 2.0.1

**Comment by tsanyqudsi** [comment]
Apparently i messed up my webpack.. loaded two `main.js` on my page. 

Fixed it with adding `inject:false` on `HtmlWebPackPlugin`

**Comment by J-Protz** [comment]
I have this same issue but I am not using HtmlWebPackPlugin.

**Comment by smenshikov** [comment]
I use Next.js and I see the same issue

**Comment by beamercola** [comment]
Gatsby and seeing same issue
