### ISSUE TITLE
My project does not have a left arrow and a right arrow

### ISSUE THREAD

**Issue by dquanghuy4444** [brainhubeu/react-carousel#660]
hi sir , i installed ur library , everything is okay but i dont see 2 arrows . i added ur code in https://brainhubeu.github.io/react-carousel/docs/examples/defaultArrows but still havent arrows . so could u solve me this issue ??
my project : https://github.com/dquanghuy4444/poshop-mobilestore
thank u so much

**Comment by RaulTsc** [comment]
+1

**Comment by chr0m1ng** [comment]
Same here, any plugin works for me

**Comment by chr0m1ng** [comment]
Ok, just found out here that the npm install is pointing to the v1, that's why it isn't working, the docs are showing the v2 but not telling people to force the install!

Just to be sure that you're in v1, try this and you'll see the arrows:
```js
<Carousel arrows>
  <img src={imageOne} />
  <img src={imageTwo} />
  <img src={imageThree} />
</Carousel>
```

Install the v2 and use the docs version and it should work!
```sh
npm i @brainhubeu/react-carousel@^2.0.1
```

**Comment by dquanghuy4444** [comment]
> Ok, just found out here that the npm install is pointing to the v1, that's why it isn't working, the docs are showing the v2 but not telling people to force the install!
> 
> Just to be sure that you're in v1, try this and you'll see the arrows:
> 
> ```js
> <Carousel arrows>
>   <img src={imageOne} />
>   <img src={imageTwo} />
>   <img src={imageThree} />
> </Carousel>
> ```
> 
> Install the v2 and use the docs version and it should work!
> 
> ```shell
> npm i @brainhubeu/react-carousel@^2.0.1
> ```

ok sir , it's work . thanks u <3
