### ISSUE TITLE
Npm pointing to v1

### ISSUE THREAD

**Issue by chr0m1ng** [brainhubeu/react-carousel#661]
The entire docs focus on v2 but the npm install command is pointing to v1! 

I've already see a few issues that could be fixed just by pointing to the newest version.

Steps to repro:
```sh
npm i @brainhubeu/react-carousel
```

Then the v1 is installed instead of v2

**Comment by MasonWang025** [comment]
Yep! Nothing from the docs work without installing v2.

**Comment by Lukasz-pluszczewski** [comment]
Hi, sorry for the delay, we have a really busy time. We'll most likely change the `latest` version to 2.0.2 soon.

**Comment by RobertHebel** [comment]
the latest channel now points to the v2
