### ISSUE TITLE
NPM is pointing to v1

### ISSUE THREAD

**Issue by davidgoldcode** [brainhubeu/react-carousel#673]

**Comment by alexgamadev** [comment]
Had about half an hour of frustration before I realised this, the docs really shouldn't point to v2 if NPM doesn't yet.

**Comment by propstg** [comment]
Wish I had looked at the github issues sooner. And wish I could say it was only half an hour of frustration here, lol.

**Comment by RobertHebel** [comment]
NPM from now on points to v2
