### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by pkocak** [brainhubeu/react-carousel#680]
Carousel doesn't support RTL. When i change my page dir RTL my images in ul with className=".BrainhubCarousel .BrainhubCarousel__trackContainer .BrainhubCarousel__track.BrainhubCarousel__track--transition" changes correctly however, this ul's translateX always gives minus number pixels.

Solution can be changing translateX to positive number pixels of ul with className=".BrainhubCarousel .BrainhubCarousel__trackContainer .BrainhubCarousel__track.BrainhubCarousel__track--transition" when page dir="rtl

**Comment by RobertHebel** [comment]
For RTL use please add the `RTL` plugin to your carousel as described here
https://brainhubeu.github.io/react-carousel/docs/examples/rtl
