### ISSUE TITLE
Touch events make buttons unresponsive on Chrome

### ISSUE THREAD

**Issue by micabe** [brainhubeu/react-carousel#70]
[Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by micabe** [comment]
Hey @mdrazyk 
Basically steps to reproduce are:
1) go on Chrome
2) turn on mobile device view
3) try to swipe on the carousel, it fails

> TLDR the lib is not working on any mobile devices that have touch enabled

**Comment by orangecms** [comment]
This looks like a duplicate of #47 which I created a fixup for :)

**Comment by micabe** [comment]
@orangecms brillant!
thanks for the fix
Waiting for your pull request dude 👍

**Comment by adam-golab** [comment]
The Pull Request is already merged. Please let us know if the issue is still present.

**Comment by piotr-s-brainhub** [comment]
@micabe @orangecms 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
