### ISSUE TITLE
Option to create styled dots

### ISSUE THREAD

**Issue by jaworek** [brainhubeu/react-carousel#77]
Looking at the current documentation it seems there is no way to create styled dots. Passing array of divs does not work:

https://codesandbox.io/s/38qqqjn4q

This is the outcome that I want to achieve:
![image](https://user-images.githubusercontent.com/22678765/48482649-8cda3980-e811-11e8-8099-fb70b3b2a327.png)

**Comment by adam-golab** [comment]
Hi @jaworek
I forked codesandbox created by you and applied some fixed. I think I'm close to what you want to achieve. There was missing import CSS from React Caroules library. Take a look at this: https://codesandbox.io/s/qvz7rwwwo4

**Comment by jaworek** [comment]
Thank you for the quick reply!

**Comment by piotr-s-brainhub** [comment]
@jaworek 

can we close this issue?

**Comment by jaworek** [comment]
Yep
