### ISSUE TITLE
Thumbnails styles break with infinite scroll

### ISSUE THREAD

**Issue by jaworek** [brainhubeu/react-carousel#82]
**Describe the bug**
Thumbnails classes are not applied when user goes into negative value with infinite scroll.

**To Reproduce**
https://codesandbox.io/s/x3k64q47qq
Press left arrow repeatedly to see the problem.

**Expected behavior**
Classes are applied to dot components all the time or there could be an option to disable them entirely.

**Comment by mdrazyk** [comment]
We will take a look at it 🙂

**Comment by udaypydi** [comment]
Hi @piotr-s-brainhub ,

Even this issue is fixed in PR: 
https://github.com/brainhubeu/react-carousel/pull/126

Thanks

**Comment by piotr-s-brainhub** [comment]
thanks @udaypydi

**Comment by pierzchalatomasz** [comment]
Closing this one since the bug is already fixed.
