### ISSUE TITLE
Slides with dynamic content show initial value when used with infinite scroll

### ISSUE THREAD

**Issue by jaworek** [brainhubeu/react-carousel#88]
**Describe the bug**
Dynamic slides do not work as intended with "infinite" prop.

**To Reproduce**
1. Go to https://codesandbox.io/s/x3k64q47qq
2. Click on -/+ buttons on the first slide.
3. Click arrows to go from last slide to the first one.
4. Notice that the initial value can be seen before current value is set.

**Expected behavior**
There should be no visible change of the values when going back and forth on the carousel.

**Screenshots**
![jan-22-2019 09-46-35](https://user-images.githubusercontent.com/22678765/51522929-ca1f0100-1e2a-11e9-8f7e-a06badccea78.gif)

**Additional context**
I made an implementation that does not have this issue (based on https://medium.com/@incubation.ff/build-your-own-css-carousel-in-react-part-one-86f71f6670ca). 

Later I'll upload demo to show how it could be implemented, although I am not sure if it would not cause big changes in the API.

I am looking for a carousel library that works correctly, but from ones that I have tested ([Swiper](http://idangero.us/swiper/), [react-slick](https://github.com/akiran/react-slick) ) all suffer from the same problem. This may be a specific need that is not required for most users, but it would be nice to have if it does not introduce big breaking changes or need to rewrite big portions of the codebase.

**Comment by damian-szulc** [comment]
Hi @jaworek 
First off, thank you for your effort of providing complete information about that issue. Unfortunately, we won't be able to look into it any time soon. In reference to the _Additional context_ would you be willing to take a look into it? There might be a straightforward fix for that. What do you say?

**Comment by jaworek** [comment]
Hi,
Sorry for late reply. I'm not working on the project related to this issue anymore.
I'll try to find a solution, when I have some spare time.

**Comment by piotr-s-brainhub** [comment]
@jaworek 

are you able to find time to fix it?
no problem if not, I just remind you because maybe you have some time available but you forgot about this issue

**Comment by jaworek** [comment]
You can close it for now.

**Comment by piotr-s-brainhub** [comment]
@jaworek 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
