### ISSUE TITLE
Positioning Neatly to Left Edge.  Trying to set slide position to consistent spot on infinite 

### ISSUE THREAD

**Issue by tayloraucoin** [brainhubeu/react-carousel#96]
Hello,

Trying to implement but running into a roadblock.

*Goal:* 
1) To have a carousel hold multiple cards, and have those cards fit neatly in the space provided.  
2) The card width would be a percentage based on the number of `slidesPerPage`. 
3) The first index position would ALWAYS line up at the left edge of the carousel space. 

*Current behavior:* 
- With infinite on: the cards never line up neatly on the left edge.  Even with `centered` turned off.  
- Without infinite on: the cards start lined up on the left edge, but do not stay that way when slid over. 

```
<Carousel
        addArrowClickHandler
        arrowLeft={ <ArrowButton className={ className_arrows }><KeyboardArrowLeft/></ArrowButton> }
        arrowRight={ <ArrowButton className={ className_arrows }><KeyboardArrowRight/></ArrowButton> }
        centered={ false }
        infinite
        slides={ slides }
        slidesPerPage={ 2 }
        >
```

Thanks for your hard work.

**Comment by damian-szulc** [comment]
Hi,
thank you for creating this issue. Would you be willing though to create a sandbox example that reproduces that issue? It would help us wrap our heads around it and most likely it would reduce time to fix that. You wouldn't have to start from scratch. I think this one: https://codesandbox.io/s/qvz7rwwwo4 might be a good starting point 👍

**Comment by colorwheeloflife** [comment]
Thank you for the prompt reply.  My apologies on the tardy return. 

Here is the problem in the sandbox you requested:  https://codesandbox.io/s/38j1k06jvp 


Please let me know your thoughts.

**Comment by colorwheeloflife** [comment]
Correction point:  

If possible, I would like the slides to each have a fixed size, and would span as far as the space allows.

So if at full window width it can show 6 items, then when window decreases width, it would only show 4, but each item's width remains intact. 

Each arrow bump would shuffle over 1 item perfectly.  Incrementing per item. Always aligning to the left index. 

Please let me know how achievable this is within the current build. 

Thank you for your time and effort.

**Comment by piotr-s-brainhub** [comment]
@tayloraucoin 

We don't have too much time but a PR is welcome.
I added `hacktoberfest` label so maybe somebody will implement this.

**Comment by tayloraucoin** [comment]
I've just built my own component from scratch that works better for my use-case.  Thank you

**Comment by piotr-s-brainhub** [comment]
Thanks @tayloraucoin 

so I close this issue

**Comment by piotr-s-brainhub** [comment]
@tayloraucoin 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
