### ISSUE TITLE
Active/Selected thumb doesn't work

### ISSUE THREAD

**Issue by AnthonyBoyer13** [brainhubeu/react-carousel#99]
**Describe the bug**
Wrong active thumb item

**To Reproduce**
Use the Carousel with thumbs and set the first active by default
Then you will see that all thumbs are "active/selected" (check CSS class)

**Expected behavior**
I would have expected that only the first thumb was active/selected

**Additional context**
In CarouselDots.js component the method "calculateButtonValue " is wrong., especially these lines:
`return this.props.value >= 0`
`      ? this.props.value`
`      : this.props.value + numberOfSlides * Math.ceil(Math.abs(this.props.value/numberOfSlides));`

Indeed, the line `this.props.value >= 0` will always return true... so all thumbs will be selected.

Can you please fix it?

Regards,

**Comment by piotr-s-brainhub** [comment]
Thanks for reporting this.
Unfortunately we don't have enough time to resolve this issue.
Anyway a PR is more than welcome.

**Comment by udaypydi** [comment]
Hi @piotr-s-brainhub ,

Here is the PR for this fix.

PR: https://github.com/brainhubeu/react-carousel/pull/126

Thanks

**Comment by piotr-s-brainhub** [comment]
thanks @udaypydi

**Comment by pierzchalatomasz** [comment]
Closing, since it's fixed

**Comment by piotr-s-brainhub** [comment]
@AnthonyBoyer13 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
